return {
    "Also try Deltarune!",
    "Dess wuz here",
    "Also try Deoxynn!",
    "Also try Starrune!",
    "Now with 50% less Ralsei!",
    "Now with extra darkness!",
    "FUCK YOU, CYBER CITY!!",
    ":]",
    "Hey all! Scott here!",
    "Now with 50% more\nSpamton!",
    "May contain nuts!",
    "More than -1 sold!",
    "It's a game!",
    "Singleplayer!",
    "Keyboard compatible!",
    "Gamepad compatible!",
    "Open source!",
    "Not on Steam!",
    "Pixels!",
    "6% bug free!",
    "Absolutely memes!",
    "Indie!",
    "Now in 2D!",
    "[Guaranteed]!",
    "Random splash!",
    "Fear of Anxiety!",
    "SMW forever!",
    "Don't look directly\nat the bugs!",
    "Kinda like Pokemon!",
    "Has an ending...planned!",
    "Deja vu!",
    "Deja vu!",
    "Mmmph, mmph!",
    "I have a PR.",
    "Fixing Magical Glass!",
    "LOVE 10 + 1 = 11!",
    "Woah.",
    "Honey, I dug the beans!‌",
    "Home-made!",
    "There's <<a dog\non ,my\nkeyboard!~",
    "RIBBIT!",
    "Potassium",
    "Can You Really Call\nThis Splash Text? I\nDidn't Gain Something\nFrom Reading It\nOr Anything",
    "Crazy? I was crazy once.",
    "All toasters toast toast!",
    "Also try RIBBIT!",
    "spring time\nback to school",
    "try to withstand\nthe sun's life-giving\nrays.",
    "sweep a leaf\nsweep away a troubles",
    "cold outside but stay\nwarm inside of you",
    "And in that light,\nI find deliverence",
    "The place that is\nbelieved to be dark",
    "Everything is going\nto be fine",
    "No one is around to help",
    "Beep Boop",
    "I've come to make\nan announcement!",
    "There is no crashes\nin Dark Place",
    "I had more splash\nideas but I forgot\nthem",
    "Smile",
    "Oh hi :D",
    "Man I love this clock",
    "Nice Strike!",
    "May include Deltarune content!",
    "May include bones!",
    "May include flesh!",
    "Good times only!",
    "I found a dog!",
    "I lost the dog...",
    "Why is there 2 dogs??",
    "Dogs!!",
    "Gangnam Style",
    "Do not ask for advice",
    "Subscribe to Bikini Spamton!",
    "Welcome to the woods",
    "Run this on a\nWii you coward",
    "Right behind you.",
    "Have a break,\nhave a legally distinct\nGitGog",
    "FRIEND INSIDE ME",
    "VERY, VERY INTERESTING",
    "Smells like splash text",
    "human... i remember\nyou're genocides...",
    "Help! They're forcing\nme to make\nsplash texts!",
    "Knockback Bros.\nbut like not\nadvanced",
    "We'll cross that bridge\nwhen we come to it.",
    "I will become back my money.",
	"Chess Battle Advanced",
	"*insert outdated meme here*",
	"Happy new year 1997!",
	"Coming straight from YOUR house",
	"GROOVY and NEVER glooby!",
	"You can't get this from an EGG!",
	"Buble",
	"I'm old!",
	"Funny text!",
	"Skippable text!",
	"Obscure references!",
	"Purification in progress",
	"Lorem ipsum docet",
	"NOT a Chapter 5 take!",
	"Improved from Legacy!",
	"See that heart? No shit!",
	"That's right! I'm the\nRoaring Knight",
	"Togore-tastic!",
    "You just lost the game!",
    "Hello Mario.",
    "NOT a Deltarune Mod!",
    "Requires arithmetics!",
    "Dessember Holiday.",
    "Dessember Holidy?",
    "Dessember Holidoy!",
    "Two trains, Train A and Train B,\nsimultaneously depart Station A\nand Station B.\nStation A and Station B are 252.5 miles\napart from each other.\nTrain A is moving at 124.7mph towards\nStation B, and Train B is moving at\n253.5mph towards station A.\nIf both trains departed at 10:00AM and it\nis now 10:08, how much longer until\nboth trains pass each other?",
    "Now with 200% less lore!",
    "Press Alt+F4 to WIN!",
    "Press Alt+F4 to LOSE!",
    "Press Alt+F4 to DIE!",
    "Do not press Alt+F4",
    "Press F4",
    "Don't forget, TESTROOM!",
    "Don't forget, 00000000!",
    "Don't forget, DESSHERE!",
    "Don't forget, FLOORONE!",
    "Don't forget, GIMMICK!",
    "Don't forget, SLIDER!",
    "Don't forget, WIFIDOWN!",
    "Don't forget, THETOWER!",
    "Don't forget, no DEVDINER!",
    "Talk to Addisons for help!",
    "Talk to Tenna for help!",
    "Talk to Ramb for help!",
    "Talk to Sans for help!",
    "AN INTERESING CONUNDRUM.",
    "I am in splashes.lua!",
}