return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 24,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 24,
  nextobjectid = 167,
  backgroundcolor = { 50, 185, 255 },
  properties = {
    ["border"] = "leaves",
    ["light"] = true,
    ["music"] = "deltarune/mus_birdnoise"
  },
  tilesets = {
    {
      name = "hometown",
      firstgid = 1,
      filename = "../../../../../tilesets/hometown.tsx",
      exportfilename = "../../../../../tilesets/hometown.lua"
    },
    {
      name = "hometownshadowsobjects",
      firstgid = 287,
      filename = "../../../../../tilesets/hometownshadowsobjects.tsx",
      exportfilename = "../../../../../tilesets/hometownshadowsobjects.lua"
    },
    {
      name = "hometowneveningtreeobjects",
      firstgid = 367,
      filename = "../../../../../tilesets/hometowneveningtreeobjects.tsx",
      exportfilename = "../../../../../tilesets/hometowneveningtreeobjects.lua"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "objects_bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 11,
          name = "ebott_bgclouds",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../../../../../assets/sprites/world/maps/ebott/overview.png",
      id = 8,
      name = "bg_ebott",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 40,
      parallaxx = 1,
      parallaxy = 0.9,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../../../../../assets/sprites/world/maps/ebott/overview_shadow.png",
      id = 20,
      name = "bg_evening_shadow",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 40,
      parallaxx = 1,
      parallaxy = 0.9,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 24,
      id = 2,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 51, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 53, 0, 0,
        51, 261, 272, 37, 272, 272, 272, 272, 272, 272, 272, 272, 39, 272, 261, 53,
        272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272,
        272, 272, 272, 272, 272, 272, 272, 272, 272, 42, 272, 272, 272, 272, 272, 272,
        60, 272, 272, 272, 272, 39, 272, 272, 272, 272, 272, 272, 272, 272, 272, 60,
        0, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 0,
        0, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 272, 272, 272, 272, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 24,
      id = 3,
      name = "Tile Layer 3",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2147483686, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 46, 46, 46, 46, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 57, 57, 57, 57, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 57, 43, 57, 57, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 57, 57, 57, 57, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 57, 57, 57, 57, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 57, 57, 57, 57, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 57, 57, 43, 57, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 57, 57, 57, 57, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 57, 57, 57, 57, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 24,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        151, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151,
        151, 152, 151, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151, 150, 151,
        151, 152, 151, 152, 0, 0, 0, 0, 0, 0, 0, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151,
        151, 152, 151, 152, 151, 152, 153, 0, 0, 149, 150, 151, 150, 151, 150, 151
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 22,
      name = "objects_evening_tree",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 960,
          width = 640,
          height = 440,
          rotation = 0,
          opacity = 1,
          gid = 402,
          visible = true,
          properties = {
            ["overcast_fade"] = true,
            ["sunset"] = 1
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 9,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 940,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "light/hometown/secret_path",
            ["marker"] = "entry_up"
          }
        },
        {
          id = 13,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 240,
          width = 240,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "ebott.lookout"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 10,
          name = "entry_pre_ebott",
          type = "",
          shape = "point",
          x = 320,
          y = 920,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 24,
      id = 7,
      name = "Tile Layer 4",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        181, 182, 183, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 177, 178, 179,
        192, 193, 194, 182, 183, 0, 0, 0, 0, 0, 0, 177, 178, 188, 189, 190,
        151, 152, 192, 193, 194, 182, 183, 0, 0, 177, 178, 188, 189, 190, 150, 151,
        0, 0, 151, 152, 192, 193, 194, 0, 0, 188, 189, 190, 150, 151, 0, 0,
        0, 0, 0, 0, 151, 152, 153, 0, 0, 149, 150, 151, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "objects_evening_treeup",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 600,
          width = 640,
          height = 198,
          rotation = 0,
          opacity = 1,
          gid = 403,
          visible = true,
          properties = {
            ["overcast_fade"] = true,
            ["sunset"] = 1
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 600,
          width = 280,
          height = 360,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 600,
          width = 280,
          height = 360,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "polygon",
          x = 0,
          y = 360,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = -40 },
            { x = 80, y = -40 },
            { x = 120, y = -80 },
            { x = 520, y = -80 },
            { x = 560, y = -40 },
            { x = 600, y = -40 },
            { x = 640, y = 0 },
            { x = 640, y = -120 },
            { x = 0, y = -120 }
          },
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "polygon",
          x = 400,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 240, y = -160 },
            { x = 240, y = 0 }
          },
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "polygon",
          x = 240,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -240, y = -160 },
            { x = -240, y = 0 }
          },
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 360,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 360,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 12,
      name = "shadows",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 19,
          name = "objects_shadows_evening_topcutout",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 18,
          name = "objects_shadows_morning_topcutout",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 14,
          name = "objects_shadows_evening_cutout",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 96,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 600,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 324,
              visible = true,
              properties = {}
            },
            {
              id = 95,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 668,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 94,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 628,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 93,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 620,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 92,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 660,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 91,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 700,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 90,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 740,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 89,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 780,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 88,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 820,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 87,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 860,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 86,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 900,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 85,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 940,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 84,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 588,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 83,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 980,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 80,
              name = "",
              type = "",
              shape = "rectangle",
              x = 210,
              y = 630,
              width = 32,
              height = 32,
              rotation = 0,
              opacity = 1,
              gid = 332,
              visible = true,
              properties = {}
            },
            {
              id = 79,
              name = "",
              type = "",
              shape = "rectangle",
              x = 164,
              y = 640,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 78,
              name = "",
              type = "",
              shape = "rectangle",
              x = 84,
              y = 600,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 77,
              name = "",
              type = "",
              shape = "rectangle",
              x = 4,
              y = 560,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 76,
              name = "",
              type = "",
              shape = "rectangle",
              x = -76,
              y = 520,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 75,
              name = "",
              type = "",
              shape = "rectangle",
              x = 364,
              y = 640,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 74,
              name = "",
              type = "",
              shape = "rectangle",
              x = 444,
              y = 600,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 73,
              name = "",
              type = "",
              shape = "rectangle",
              x = 524,
              y = 560,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 72,
              name = "",
              type = "",
              shape = "rectangle",
              x = 604,
              y = 520,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 97,
              name = "",
              type = "",
              shape = "rectangle",
              x = 0,
              y = 960,
              width = 80,
              height = 480,
              rotation = 0,
              opacity = 1,
              gid = 332,
              visible = true,
              properties = {}
            },
            {
              id = 98,
              name = "",
              type = "",
              shape = "rectangle",
              x = 80,
              y = 960,
              width = 80,
              height = 440,
              rotation = 0,
              opacity = 1,
              gid = 332,
              visible = true,
              properties = {}
            },
            {
              id = 99,
              name = "",
              type = "",
              shape = "rectangle",
              x = 160,
              y = 960,
              width = 80,
              height = 400,
              rotation = 0,
              opacity = 1,
              gid = 332,
              visible = true,
              properties = {}
            },
            {
              id = 101,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 748,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 102,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 708,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 103,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 828,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 104,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 788,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 105,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 908,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 106,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 868,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 107,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 988,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 108,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 948,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 15,
          name = "objects_shadows_morning_cutout",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 24,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 600,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 324,
              visible = true,
              properties = {}
            },
            {
              id = 28,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 668,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 29,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 628,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 34,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 620,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 35,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 660,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 36,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 700,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 37,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 740,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 38,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 780,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 39,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 820,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 40,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 860,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 41,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 900,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 42,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 940,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 44,
              name = "",
              type = "",
              shape = "rectangle",
              x = 234,
              y = 588,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 323,
              visible = true,
              properties = {}
            },
            {
              id = 53,
              name = "",
              type = "",
              shape = "rectangle",
              x = 360,
              y = 980,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 331,
              visible = true,
              properties = {}
            },
            {
              id = 54,
              name = "",
              type = "",
              shape = "rectangle",
              x = 460,
              y = 720,
              width = 130,
              height = 200,
              rotation = 0,
              opacity = 1,
              gid = 332,
              visible = true,
              properties = {}
            },
            {
              id = 55,
              name = "",
              type = "",
              shape = "rectangle",
              x = 560,
              y = 720,
              width = 80,
              height = 240,
              rotation = 0,
              opacity = 1,
              gid = 332,
              visible = true,
              properties = {}
            },
            {
              id = 68,
              name = "",
              type = "",
              shape = "rectangle",
              x = 210,
              y = 630,
              width = 32,
              height = 32,
              rotation = 0,
              opacity = 1,
              gid = 332,
              visible = true,
              properties = {}
            },
            {
              id = 16,
              name = "",
              type = "",
              shape = "rectangle",
              x = 164,
              y = 640,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 17,
              name = "",
              type = "",
              shape = "rectangle",
              x = 84,
              y = 600,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 18,
              name = "",
              type = "",
              shape = "rectangle",
              x = 4,
              y = 560,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 19,
              name = "",
              type = "",
              shape = "rectangle",
              x = -76,
              y = 520,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 20,
              name = "",
              type = "",
              shape = "rectangle",
              x = 364,
              y = 640,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 21,
              name = "",
              type = "",
              shape = "rectangle",
              x = 444,
              y = 600,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 22,
              name = "",
              type = "",
              shape = "rectangle",
              x = 524,
              y = 560,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            },
            {
              id = 23,
              name = "",
              type = "",
              shape = "rectangle",
              x = 604,
              y = 520,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 334,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 17,
          name = "objects_shadows_evening",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 109,
              name = "",
              type = "",
              shape = "rectangle",
              x = 240,
              y = 960,
              width = 140,
              height = 400,
              rotation = 0,
              opacity = 1,
              gid = 346,
              visible = true,
              properties = {}
            },
            {
              id = 117,
              name = "",
              type = "",
              shape = "rectangle",
              x = 290,
              y = 560,
              width = 119,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 1073742178,
              visible = true,
              properties = {}
            },
            {
              id = 127,
              name = "",
              type = "",
              shape = "rectangle",
              x = 386,
              y = 500,
              width = 110,
              height = 24,
              rotation = 90,
              opacity = 1,
              gid = 354,
              visible = true,
              properties = {}
            },
            {
              id = 128,
              name = "",
              type = "",
              shape = "rectangle",
              x = 400,
              y = 510,
              width = 110,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 1073742178,
              visible = true,
              properties = {}
            },
            {
              id = 129,
              name = "",
              type = "",
              shape = "rectangle",
              x = 466,
              y = 460,
              width = 110,
              height = 24,
              rotation = 90,
              opacity = 1,
              gid = 354,
              visible = true,
              properties = {}
            },
            {
              id = 130,
              name = "",
              type = "",
              shape = "rectangle",
              x = 480,
              y = 470,
              width = 110,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 1073742178,
              visible = true,
              properties = {}
            },
            {
              id = 134,
              name = "",
              type = "",
              shape = "rectangle",
              x = 546,
              y = 420,
              width = 110,
              height = 24,
              rotation = 90,
              opacity = 1,
              gid = 354,
              visible = true,
              properties = {}
            },
            {
              id = 135,
              name = "",
              type = "",
              shape = "rectangle",
              x = 560,
              y = 430,
              width = 110,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 1073742178,
              visible = true,
              properties = {}
            },
            {
              id = 138,
              name = "",
              type = "",
              shape = "rectangle",
              x = 410,
              y = 540,
              width = 60,
              height = 30,
              rotation = 0,
              opacity = 1,
              gid = 346,
              visible = true,
              properties = {}
            },
            {
              id = 139,
              name = "",
              type = "",
              shape = "rectangle",
              x = 490,
              y = 500,
              width = 60,
              height = 30,
              rotation = 0,
              opacity = 1,
              gid = 346,
              visible = true,
              properties = {}
            },
            {
              id = 140,
              name = "",
              type = "",
              shape = "rectangle",
              x = 570,
              y = 460,
              width = 60,
              height = 30,
              rotation = 0,
              opacity = 1,
              gid = 346,
              visible = true,
              properties = {}
            },
            {
              id = 141,
              name = "",
              type = "",
              shape = "rectangle",
              x = 210,
              y = 560,
              width = 119,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 1073742178,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 23,
          name = "objects_evening_shadow_collision",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 142,
              name = "eveningshadowfull",
              type = "",
              shape = "rectangle",
              x = 240,
              y = 550,
              width = 160,
              height = 408,
              rotation = 0,
              opacity = 1,
              visible = true,
              properties = {
                ["sunset"] = 1
              }
            },
            {
              id = 151,
              name = "eveningshadowfull",
              type = "",
              shape = "rectangle",
              x = 400,
              y = 506,
              width = 80,
              height = 94,
              rotation = 0,
              opacity = 1,
              visible = true,
              properties = {
                ["sunset"] = 1
              }
            },
            {
              id = 155,
              name = "eveningshadowfull",
              type = "",
              shape = "rectangle",
              x = 408,
              y = 498,
              width = 72,
              height = 8,
              rotation = 0,
              opacity = 1,
              visible = true,
              properties = {
                ["sunset"] = 1
              }
            },
            {
              id = 158,
              name = "eveningshadowfull",
              type = "",
              shape = "rectangle",
              x = 480,
              y = 466,
              width = 80,
              height = 134,
              rotation = 0,
              opacity = 1,
              visible = true,
              properties = {
                ["sunset"] = 1
              }
            },
            {
              id = 159,
              name = "eveningshadowfull",
              type = "",
              shape = "rectangle",
              x = 488,
              y = 458,
              width = 72,
              height = 8,
              rotation = 0,
              opacity = 1,
              visible = true,
              properties = {
                ["sunset"] = 1
              }
            },
            {
              id = 160,
              name = "eveningshadowfull",
              type = "",
              shape = "rectangle",
              x = 560,
              y = 428,
              width = 80,
              height = 172,
              rotation = 0,
              opacity = 1,
              visible = true,
              properties = {
                ["sunset"] = 1
              }
            },
            {
              id = 161,
              name = "eveningshadowfull",
              type = "",
              shape = "rectangle",
              x = 568,
              y = 420,
              width = 72,
              height = 8,
              rotation = 0,
              opacity = 1,
              visible = true,
              properties = {
                ["sunset"] = 1
              }
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 16,
          name = "objects_shadows_morning",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 56,
              name = "",
              type = "",
              shape = "rectangle",
              x = 376,
              y = 764,
              width = 62.5685,
              height = 225.194,
              rotation = -45,
              opacity = 1,
              gid = 346,
              visible = true,
              properties = {}
            },
            {
              id = 57,
              name = "",
              type = "",
              shape = "rectangle",
              x = 280,
              y = 960,
              width = 100,
              height = 280,
              rotation = 0,
              opacity = 1,
              gid = 346,
              visible = true,
              properties = {}
            },
            {
              id = 66,
              name = "",
              type = "",
              shape = "rectangle",
              x = 280,
              y = 680,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 346,
              visible = true,
              properties = {}
            },
            {
              id = 58,
              name = "",
              type = "",
              shape = "rectangle",
              x = 266,
              y = 700,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 349,
              visible = true,
              properties = {}
            },
            {
              id = 59,
              name = "",
              type = "",
              shape = "rectangle",
              x = 266,
              y = 740,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 349,
              visible = true,
              properties = {}
            },
            {
              id = 60,
              name = "",
              type = "",
              shape = "rectangle",
              x = 266,
              y = 780,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 349,
              visible = true,
              properties = {}
            },
            {
              id = 61,
              name = "",
              type = "",
              shape = "rectangle",
              x = 266,
              y = 820,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 349,
              visible = true,
              properties = {}
            },
            {
              id = 62,
              name = "",
              type = "",
              shape = "rectangle",
              x = 266,
              y = 860,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 349,
              visible = true,
              properties = {}
            },
            {
              id = 63,
              name = "",
              type = "",
              shape = "rectangle",
              x = 266,
              y = 900,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 349,
              visible = true,
              properties = {}
            },
            {
              id = 64,
              name = "",
              type = "",
              shape = "rectangle",
              x = 266,
              y = 940,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 349,
              visible = true,
              properties = {}
            },
            {
              id = 65,
              name = "",
              type = "",
              shape = "rectangle",
              x = 266,
              y = 980,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 349,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 24,
          id = 11,
          name = "tiles_shadows_evening",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 24,
          id = 13,
          name = "tiles_shadows_morning",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_overlay",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 14,
          name = "hometowndaynight",
          type = "",
          shape = "point",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
