return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 29,
  properties = {
    ["music"] = "demonic_little_grey_cliffs"
  },
  tilesets = {
    {
      name = "cliffs",
      firstgid = 1,
      filename = "../../tilesets/cliffs.tsx",
      exportfilename = "../../tilesets/cliffs.lua"
    },
    {
      name = "cliffs_objs",
      firstgid = 64,
      filename = "../../tilesets/cliffs_objs.tsx",
      exportfilename = "../../tilesets/cliffs_objs.lua"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects_bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 2,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 0,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        31, 32, 33, 0, 0, 0, 0, 13, 15, 0, 0, 0, 0, 0, 22, 23,
        40, 41, 42, 0, 0, 0, 0, 13, 15, 0, 0, 0, 0, 0, 31, 32,
        49, 50, 51, 0, 4, 5, 5, 35, 34, 5, 5, 6, 0, 0, 40, 41,
        0, 0, 0, 0, 13, 7, 14, 14, 16, 14, 7, 15, 0, 0, 49, 50,
        0, 0, 0, 0, 13, 14, 8, 7, 14, 14, 17, 15, 0, 0, 0, 0,
        0, 0, 0, 0, 13, 17, 14, 14, 14, 14, 14, 15, 0, 0, 0, 0,
        0, 0, 0, 0, 13, 7, 14, 17, 8, 14, 16, 15, 0, 0, 0, 0,
        0, 0, 0, 0, 13, 14, 14, 14, 14, 14, 8, 15, 0, 0, 0, 0,
        0, 0, 0, 0, 13, 14, 14, 7, 14, 17, 14, 15, 0, 0, 0, 0,
        5, 6, 0, 0, 13, 16, 8, 14, 16, 14, 7, 15, 0, 0, 0, 0,
        14, 15, 0, 0, 22, 23, 23, 26, 25, 23, 23, 24, 0, 0, 0, 0,
        23, 24, 0, 0, 40, 41, 41, 13, 15, 41, 41, 42, 0, 0, 0, 4
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 0,
          width = 120,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 0,
          width = 120,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 80,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 80,
          width = 40,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 440,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 440,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 80,
          width = 40,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = -40,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "grey_cliffside/cave_2",
            ["marker"] = "entry"
          }
        },
        {
          id = 8,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 480,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "grey_cliffside/cliffside_right",
            ["marker"] = "cave_exit"
          }
        },
        {
          id = 9,
          name = "enemy",
          type = "",
          shape = "point",
          x = 240,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "pebblin",
            ["chase"] = true,
            ["encounter"] = "2pebblin",
            ["facing"] = "right",
            ["group"] = "1"
          }
        },
        {
          id = 11,
          name = "enemy",
          type = "",
          shape = "point",
          x = 400,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "pebblin",
            ["chase"] = true,
            ["encounter"] = "2pebblin",
            ["group"] = "1"
          }
        },
        {
          id = 12,
          name = "glitch_bg",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 240,
          width = 70,
          height = 136,
          rotation = 0,
          gid = 64,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 148,
          y = 414,
          width = 180,
          height = 168,
          rotation = 0,
          gid = 65,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 120,
          width = 180,
          height = 168,
          rotation = 0,
          gid = 65,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 14,
          name = "entry",
          type = "",
          shape = "point",
          x = 320,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
