return {
    a = function(cutscene)
        cutscene:showNametag("Susie")
        cutscene:text("* Well,[wait:5] it looks like our journey is reaching its end...", "neutral_side", "susie")
        cutscene:text("* To be honest,[wait:5] I'm kinda glad I didn't listen to Ralsei.", "small_smile", "susie")
        cutscene:text("* I mean,[wait:5] sure,[wait:5] I did almost destroy reality,[wait:5] but...", "shy_b", "susie")
        cutscene:text("* I've made so many friends along the way.", "sincere_smile", "susie")
        cutscene:hideNametag()
    end,

    b = function(cutscene)
        cutscene:showNametag("Susie")
        cutscene:text("* I remember back when I opened that closet door...", "neutral_side", "susie")
        cutscene:text("* ... and entered the Dark World for the first time.", "neutral", "susie")
        cutscene:text("* I know it hasn't been that long since then,[wait:5] but it feels like years.", "smirk", "susie")
        cutscene:text("* Man,[wait:5] I really did have so much fun going on those adventures.", "smile", "susie")
        cutscene:text("* But...[wait:10] Soon I might not ever be able to go on those again...", "shy_down", "susie")
        cutscene:hideNametag()
    end,

    c = function(cutscene)
        cutscene:showNametag("Susie")
        cutscene:text("* I mean sure,[wait:5] there's still gonna be a few Dark Worlds,[wait:5] but...", "nervous", "susie")
        cutscene:text("* You can only do so much in one of them...", "annoyed_down", "susie")
        cutscene:text("* That's sorta WHY I made so many Dark Fountains.", "neutral", "susie")
        cutscene:text("* I could never forget the thrill of a new adventure.", "smile", "susie")
        cutscene:text("* To be honest,[wait:5] I'm gonna miss all of this...", "smirk", "susie")
        cutscene:hideNametag()
    end,

    d = function(cutscene)
        cutscene:showNametag("Susie")
        cutscene:text("* But,[wait:5] y'know what they say.", "neutral", "susie")
        cutscene:text("* 'Don't cry because it's over,[wait:5] smile because it happened.'", "small_smile", "susie")
        cutscene:text("* Or something cheesy like that.", "smirk", "susie")
        cutscene:text("* I still have the memories of all those Dark Worlds.", "smile", "susie")
        cutscene:text("* And really,[wait:5] that's all that matters,[wait:5] right?", "sincere_smile", "susie")
        cutscene:hideNametag()
    end,

    dessimation = function(cutscene)
        if Game:getPartyMember("dess").love >= 15 then
            local susie = cutscene:getCharacter("susie")
            local dess = cutscene:getCharacter("dess")
            cutscene:detachCamera()
            cutscene:panTo(2440, 360, 2)
            cutscene:walkTo(Game.world.player, Game.world.player.x + 120, 360, 1.5, "right")
            cutscene:wait(2)
            cutscene:showNametag("Dess")
            if Game:hasPartyMember("dess") then
                cutscene:text("* hey guys wait a minute", "neutral_b", "dess")
                cutscene:hideNametag()
                cutscene:walkTo(dess, 2600, 360, 5, "right")
                cutscene:wait(6)
                cutscene:showNametag("Dess")
                cutscene:text("* you smell that?", "doom", "dess")
                cutscene:text("* that's the smell of some free exp up ahead", "doom_shiteatinggrin", "dess")
                cutscene:showNametag("Susie")
                susie:setSprite("exasperated_right")
                cutscene:text("* Oh my GOD.", "angry_b", "susie")
                cutscene:text("* Can you not try to kill something for FIVE SECONDS?", "angry", "susie")
                susie:resetSprite()
                cutscene:text("* We're here to find Ralsei,[wait:5] nothing more,[wait:5] nothing less.", "annoyed", "susie")
                cutscene:showNametag("Dess")
                Game.world.music:stop()
                dess:setFacing("left")
                cutscene:text("* who said im not here for ralsei too?", "condescending", "dess")
                cutscene:showNametag("Susie")
                cutscene:text("* What do you...", "suspicious", "susie")
            else
                cutscene:text("* so...", "neutral_c", "dess")
                cutscene:text("* youre finally here...", "neutral", "dess")
                cutscene:showNametag("Susie")
                cutscene:text("* Wh-", "shock", "susie")
                cutscene:text("* How the hell did you get here!?", "angry", "susie")
                cutscene:showNametag("Dess")
                dess:setFacing("left")
                cutscene:text("* a magician never reveals their secrets", "condescending", "dess")
                cutscene:text("* i bet you thought you could just cast me aside", "annoyed", "dess")
                cutscene:text("* 'i don't need dess,[wait:5] i can kill all these people all on my own'", "calm", "dess")
                cutscene:showNametag("Susie")
                cutscene:text("* We're NOT here to kill people.", "annoyed", "susie")
                cutscene:text("* We're here to find Ralsei.", "annoyed_down", "susie")
                cutscene:showNametag("Dess")
                cutscene:text("* oh yeah?", "eyebrow", "dess")
                Game.world.music:stop()
                cutscene:text("* well im here to kill ralsei,[wait:5] so tough luck buttercup", "condescending", "dess")
            end
            cutscene:hideNametag()
            susie:alert()
            susie:setSprite("shock_right")
            cutscene:wait(0.7)
            susie:setSprite("battle/attackready_1")
            Assets.playSound("ui_cancel_small")
            cutscene:wait(cutscene:slideTo(susie, susie.x - 40, susie.y + 20, 0.5, "out-cubic"))
            Game.world.music:play("deltarune/d", 1, 1)
            cutscene:showNametag("Susie")
            cutscene:text("* Lay a finger on him and you're DEAD!", "angry_c", "susie")
            cutscene:showNametag("Dess")
            cutscene:text("* damn bro no need to get so upset at me", "eyebrow", "dess")
            cutscene:text("* all i wanna do is kill your friend", "genuine_b", "dess")
            cutscene:showNametag("Susie")
            cutscene:text("* Are you INSANE?!", "angry_b", "susie")
            cutscene:text("* Why would I NOT be upset with you?!", "angry_c", "susie")
            cutscene:showNametag("Dess")
            cutscene:text("* we killed like almost everyone and THIS is where you draw the line?", "angry", "dess")
            cutscene:text("* tbh susie...[wait:10] i thought we could rule together...", "neutral_b", "dess")
            cutscene:text("* but i guess i was wrong", "neutral", "dess")
            cutscene:showNametag("Susie")
            cutscene:text("* Why would I ever want to work with YOU?!", "angry_c", "susie")
            cutscene:text("* You're hands-down the single worst person I've ever met!", "angry", "susie")
            cutscene:showNametag("Dess")
            cutscene:text("* aww how sweet of you", "teehee", "dess")
            cutscene:text("* unfortunately it looks like you're gonna get in my way...", "neutral_c", "dess")
            cutscene:hideNametag()
            dess:setAnimation("battle/intro")
            dess.flip_x = true
            Assets.playSound("ui_cancel_small")
            cutscene:wait(0.75)
            dess:setAnimation("battle/idle")
            cutscene:showNametag("Dess")
            cutscene:text("* oh well,[wait:5] just more experience for me", "smug", "dess")
            cutscene:hideNametag()
            Game.world.music:stop()
            Assets.playSound("laz_c", 1, 0.8)
            susie:setAnimation("battle/attack")
            cutscene:wait(1)
            susie:setAnimation("battle/idle")
            cutscene:showNametag("Susie")
            cutscene:text("* Bring it.", "bangs_teeth", "susie")
            cutscene:hideNametag()
            Game:removePartyMember("dess")
            local encounter = cutscene:startEncounter("dess", true, {{"dess", dess}})
            cutscene:wait(1)
            Game:setFlag("sus_serious", true)
            Game:getPartyMember("susie").actor.default = "walk_bangs_unhappy"
            susie:resetSprite()
            susie:shake(5)
            Assets.playSound("ui_cancel_small")
            cutscene:wait(1)
            cutscene:showNametag("Susie")
            cutscene:text("* ...", "bangs_neutral", "susie")
            cutscene:text("* I...", "annoyed_down", "susie")
            cutscene:text("* Let's just keep going.", "bangs_neutral", "susie")
            cutscene:hideNametag()
            cutscene:interpolateFollowers()
            cutscene:wait(cutscene:attachCamera(2))
        end
    end,
}