return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 25,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 9,
  nextobjectid = 54,
  properties = {
    ["border"] = "none",
    ["music"] = "deltarune/birds_ch5",
    ["name"] = "Garden Floor - Elevator"
  },
  tilesets = {
    {
      name = "tree_objects",
      firstgid = 1,
      filename = "../../tilesets/tree_objects.tsx"
    },
    {
      name = "grassdark",
      firstgid = 5,
      filename = "../../tilesets/grassdark.tsx",
      exportfilename = "../../tilesets/grassdark.lua"
    },
    {
      name = "garden_objects",
      firstgid = 221,
      filename = "../../tilesets/garden_objects.tsx"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 25,
      id = 8,
      name = "tiles_grass",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 6, 62, 62, 86, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 14, 70, 70, 94, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 14, 70, 70, 94, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 6, 62, 70, 70, 70, 70, 62, 86, 0, 0, 0, 0,
        0, 0, 0, 0, 14, 70, 70, 70, 70, 70, 70, 94, 0, 0, 0, 0,
        0, 0, 0, 0, 70, 70, 70, 70, 70, 70, 70, 70, 6, 6, 6, 6,
        0, 0, 0, 0, 70, 70, 70, 70, 70, 70, 70, 70, 102, 102, 102, 102,
        0, 0, 0, 0, 14, 70, 70, 70, 70, 70, 70, 94, 0, 0, 0, 0,
        0, 0, 0, 0, 22, 78, 70, 70, 70, 70, 78, 78, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 14, 70, 70, 94, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 22, 70, 70, 102, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 94, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 94, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 94, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 94, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 94, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 94, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 182, 198, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 182, 198, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 174, 190, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 160,
          width = 60,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 380,
          y = 160,
          width = 60,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 200,
          width = 80,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 640,
          width = 40,
          height = 360,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 640,
          width = 40,
          height = 360,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 200,
          width = 80,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 560,
          width = 80,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 560,
          width = 80,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 320,
          width = 160,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 480,
          width = 160,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 320,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects_elevator",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 9,
          name = "elevatordoor",
          type = "",
          shape = "rectangle",
          x = 260,
          y = 160,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["double_doors"] = "true",
            ["type"] = "great"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 11,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 140,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "hub_elevator",
            ["marker"] = "entry"
          }
        },
        {
          id = 26,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 1000,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "floorgarden/floradinn_encounter",
            ["marker"] = "entry_down"
          }
        },
        {
          id = 48,
          name = "dogconegroup",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["default_state"] = true
          }
        },
        {
          id = 49,
          name = "dogconegroup",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["default_state"] = true
          }
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 420,
          y = 760,
          width = 44,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 225,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 460,
          y = 880,
          width = 44,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 2147483873,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 760,
          width = 44,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 2147483873,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 880,
          width = 44,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 225,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects_trees",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 24,
          name = "entry_elevator",
          type = "",
          shape = "point",
          x = 320,
          y = 250,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "entry_up",
          type = "",
          shape = "point",
          x = 320,
          y = 960,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "spawn",
          type = "",
          shape = "point",
          x = 320,
          y = 520,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
