return {
    ---@param cutscene WorldCutscene

    call = function(cutscene, event)
        if Game:hasDLC("dlc_digimon") and (#Game.party == 1 and Game:hasPartyMember("hero")) and Game:getFlag("jamm_closure") == true and Game:getFlag("marcy_unlocked") == true and (Game:hasUnlockedPartyMember("dess") and Game:hasUnlockedPartyMember("susie") and Game:hasUnlockedPartyMember("noelle") and Game:hasUnlockedPartyMember("brenda")) and (Game:hasUnlockedPartyMember("ceroba") or Game:getFlag("whatevertheflagfordeadcerobais") == true) then
            Game:setFlag("hometown_digicall", true)
            Game:setFlag("hometown_digisetup", true)
            Game.world.music:stop()
            Assets.playSound("phone")
            cutscene:wait(1)
            Assets.playSound("phone")
            cutscene:wait(1)
            Assets.playSound("phone")
            cutscene:wait(1)
            cutscene:showNametag("Hero")
            cutscene:text("* ... Huh?", "shocked", "hero")
            cutscene:text("* That's...[wait:5] odd...", "pout", "hero")
            cutscene:text("* I don't have a phone,[wait:5] but...[wait:10] There's a ring coming from my pocket...", "suspicious", "hero")
            cutscene:text("* Might as well see what it is...", "neutral_closed", "hero")
            cutscene:hideNametag()
            Assets.playSound("item")
            cutscene:wait(0.5)
            cutscene:showNametag("Hero")
            cutscene:text("* Hello...?", "neutral_closed_b", "hero")
            cutscene:showNametag("???")
            cutscene:text("* Greetings, Hero.")
            cutscene:text("* You,[wait:5] along side seven other people,[wait:5] have been chosen for something very special.")
            cutscene:text("* Please make your way to the library.")
            cutscene:text("* Once all eight of you make it,[wait:5] open the door to the computer lab.")
            cutscene:text("* Your destiny awaits,[wait:5] Hero.")
            cutscene:hideNametag()
            Assets.playSound("item")
            cutscene:text("[voice:nil]* (Click)")
            cutscene:showNametag("Hero")
            cutscene:text("* ...", "shocked", "hero")
            cutscene:text("* What WAS that...?", "shocked", "hero")
            local hero = cutscene:getCharacter("hero_lw")
            hero:setFacing("down")
            cutscene:text("* Do YOU have any idea who that was?", "neutral_closed_b", "hero")
            cutscene:hideNametag()
            local choice = cutscene:choicer({"No clue", "Could be\nGaster?"})
            cutscene:showNametag("Hero")
            if choice == 1 then
                cutscene:text("* That makes two of us then.", "neutral_closed", "hero")
                cutscene:text("* Well,[wait:5] we should see who,[wait:5] or what,[wait:5] called me.", "neutral_closed_b", "hero")
            else
                cutscene:text("* ...", "really", "hero")
                cutscene:text("* I've talked with Gaster before,[wait:5] he sounds nothing like that.", "pout", "hero")
                cutscene:text("* Seriously,[wait:5] what is up with people nowadays...", "suspicious", "hero")
                cutscene:text("* ... thinking everything is related to him?", "suspicious", "hero")
                cutscene:text("* Uh,[wait:5] regardless,[wait:5] [face:neutral_closed]we should head to the library.", "shocked", "hero")
            end
            cutscene:hideNametag()
            hero:setFacing("up")
            event:remove()
        end
    end,

    wrongway_a = function(cutscene, event)
        if Game:getFlag("hometown_digisetup") == true then
            cutscene:showNametag("Hero")
            cutscene:text("* That's the wrong way.", "neutral_closed", "hero")
            cutscene:hideNametag()
            local hero = cutscene:getCharacter("hero_lw")
            cutscene:wait(cutscene:walkTo(hero, hero.x, hero.y - 80, 1))
        end
    end,

    wrongway_b = function(cutscene, event)
        if Game:getFlag("hometown_digisetup") == true then
            cutscene:showNametag("Hero")
            cutscene:text("* That's the wrong way.", "neutral_closed", "hero")
            cutscene:hideNametag()
            local hero = cutscene:getCharacter("hero_lw")
            cutscene:wait(cutscene:walkTo(hero, hero.x + 80, hero.y, 1))
        end
    end,

    wrongway_c = function(cutscene, event)
        if Game:getFlag("hometown_digisetup") == true then
            cutscene:showNametag("Hero")
            cutscene:text("* That's the wrong way.", "neutral_closed", "hero")
            cutscene:hideNametag()
            local hero = cutscene:getCharacter("hero_lw")
            cutscene:wait(cutscene:walkTo(hero, hero.x - 80, hero.y, 1))
        end
    end,

    wrongway_d = function(cutscene, event)
        if Game:getFlag("hometown_digisetup") == true then
            cutscene:showNametag("Hero")
            cutscene:text("* That's the wrong way.", "neutral_closed", "hero")
            cutscene:hideNametag()
            local hero = cutscene:getCharacter("hero_lw")
            cutscene:wait(cutscene:walkTo(hero, hero.x, hero.y + 80, 1))
        end
    end,

    library = function(cutscene, event)
        local hero = cutscene:getCharacter("hero_lw")
        local susie = cutscene:getCharacter("susie_lw")
        local noelle = cutscene:getCharacter("noelle_lw")
        local dess = cutscene:getCharacter("dess")
        local ceroba = cutscene:getCharacter("ceroba")
        local brenda = cutscene:getCharacter("brenda_lw")
        local jammarcy = cutscene:getCharacter("jammarcy_light")
        Game.world.music:fade(0, 0.5)
        cutscene:walkTo(hero, hero.x, hero.y - 40, 2)
        cutscene:wait(0.5)
        susie:alert()
        noelle:alert()
        dess:alert()
        ceroba:alert()
        brenda:alert()
        jammarcy:alert()
        cutscene:wait(0.5)
        susie:resetSprite()
        dess:setFacing("left")
        ceroba:setFacing("down")
        brenda:setFacing("left")
        jammarcy:setFacing("right")
        cutscene:showNametag("Susie", {top = false})
        cutscene:text("* Hero?[wait:5] The hell're you doing here?", "surprise", "susie", {top = false})
        cutscene:text("* Wait,[wait:5] did you get a weird phone-call too?", "annoyed", "susie", {top = false})
        cutscene:showNametag("Hero")
        cutscene:text("* Yup,[wait:5] I'm guessing you guys all had that call too?", "neutral_closed_b", "hero")
        cutscene:showNametag("Ceroba", {top = false})
        cutscene:text("* Mhm.", "closed_eyes", "ceroba", {top = false})
        cutscene:showNametag("Brenda")
        cutscene:text("* Yeah,[wait:5] I got kinda spooked because I almost never get calls.", "smile_b", "brenda_lw")
        cutscene:showNametag("Noelle", {top = false})
        cutscene:text("* Me too,[wait:5] I a-almost had a heart attack, fahah!", "blush_finger", "noelle", {top = false})
        cutscene:showNametag("Dess")
        cutscene:text("* oh yeah,[wait:5] i'm the chosen one, baby", "heckyeah", "dess")
        cutscene:showNametag("Jamm")
        cutscene:text("* You're acting like you're the only one who got this call.", "suspicious", "jamm")
        cutscene:showNametag("Marcy")
        cutscene:text("* Papa,[wait:5] this makes Marcy special,[wait:5] right?", "smile", "marcy")
        cutscene:showNametag("Jamm")
        cutscene:text("* You've always been special, Marcy.", "side_smile", "jamm")
        cutscene:text("* I guess this just makes you even more special,[wait:5] haha!", "happy", "jamm")
        cutscene:showNametag("Ceroba", {top = false})
        cutscene:text("* ...", "dissapproving_1", "ceroba", {top = false})
        cutscene:text("* So,[wait:5] I suppose that makes all eight of us here?", "neutral", "ceroba", {top = false})
        cutscene:showNametag("Hero")
        cutscene:text("* Looks like it.", "neutral_closed", "hero")
        cutscene:text("* You guys ready to head into the computer lab?", "neutral_closed_b", "hero")
        cutscene:showNametag("Susie", {top = false})
        cutscene:text("* Yeah,[wait:5] you head in whenever you're ready,[wait:5] and we'll follow.", "smirk", "susie", {top = false})
        cutscene:showNametag("Hero")
        cutscene:text("* Got it.", "happy", "hero")
        cutscene:hideNametag()
        susie:setSprite("chill")
        dess:setFacing("up")
        ceroba:setFacing("left")
        brenda:setFacing("right")
        jammarcy:setFacing("up")
    end,

    wrongway_library = function(cutscene, event)
        if Game:getFlag("hometown_digisetup") == true then
            cutscene:showNametag("Hero")
            cutscene:text("* No going back now.", "neutral_closed", "hero")
            cutscene:hideNametag()
            local hero = cutscene:getCharacter("hero_lw")
            cutscene:wait(cutscene:walkTo(hero, hero.x, hero.y - 80, 1))
        end
    end,

    brenda = function(cutscene, event)
        if cutscene:getCharacter("hero_lw").facing == "right" then
            event:setFacing("left")
        else
            event:setFacing("up")
        end
        cutscene:showNametag("Brenda")
        cutscene:text("* Man,[wait:5] I wonder who was calling us.", "down", "brenda_lw")
        cutscene:text("* It wasn't a voice I recognized,[wait:5] so it can't be anyone I know.", "neutral", "brenda_lw")
        cutscene:hideNametag()
        event:setFacing("right")
    end,

    dess = function(cutscene, event)
        event:setFacing("left")
        cutscene:showNametag("Dess")
        cutscene:text("* hell yeah i'm special and you guys are not", "condescending", "dess")
        cutscene:getCharacter("jammarcy_light"):setFacing("right")
        cutscene:showNametag("Jamm")
        cutscene:text("* Didn't I just say we all got this call?", "determined", "jamm")
        cutscene:showNametag("Dess")
        cutscene:text("* lalalalala can't hear you", "calm_b", "dess")
        cutscene:hideNametag()
        event:setFacing("up")
        cutscene:getCharacter("jammarcy_light"):setFacing("up")
    end,

    ceroba = function(cutscene, event)
        cutscene:showNametag("Ceroba")
        cutscene:text("* I'm worried that this could be a trap.", "dissapproving", "ceroba")
        cutscene:showNametag("Susie")
        cutscene:text("* Nah,[wait:5] I don't think there's anyone in town that'd do that.", "neutral_side", "susie")
        cutscene:text("* If anything,[wait:5] it's gonna be a surprise party!", "smile", "susie")
        cutscene:text("* Man I hope there's lots of cake,[wait:5] ice cream,[wait:5]\nham sandwiches...", "sincere_smile", "susie")
        cutscene:showNametag("Ceroba")
        cutscene:text("* ...[wait:10]\n[face:unsure_alt]* You're drooling.", "wat", "ceroba")
        cutscene:showNametag("Susie")
        cutscene:text("* Oh,[wait:5] oops.", "shock_down", "susie")
        cutscene:text("* Besides,[wait:5] even if it IS a trap...", "closed_grin", "susie")
        cutscene:text("* We can just kick the ass of whoever's behind it to next Sunday.", "teeth_smile", "susie")
        cutscene:showNametag("Ceroba")
        cutscene:text("* I guess you're right,[wait:5] Susie.", "closed_eyes", "ceroba")
        cutscene:showNametag("Susie")
        cutscene:text("* I'm always right!", "closed_grin", "susie")
        cutscene:text("* Uh,[wait:5] except for when I'm not.", "shock_nervous", "susie")
        cutscene:hideNametag()
    end,

    susie = function(cutscene, event)
        cutscene:showNametag("Susie")
        cutscene:text("* You can go in whenever you're ready, Hero.", "neutral", "susie")
        cutscene:text("* We'll be right behind you!", "sincere_smile", "susie")
        cutscene:hideNametag()
    end,

    noelle = function(cutscene, event)
        if cutscene:getCharacter("hero_lw").facing == "left" then
            event:setFacing("right")
        end
        cutscene:showNametag("Noelle")
        cutscene:text("* G-gosh,[wait:5] I h-hope there isn't some sorta prank waiting for us.", "blush_smile", "noelle")
        cutscene:text("* I think I'd literally DIE if it's Kris trying to spook me again,[wait:5] faha!", "blush_smile_closed", "noelle")
        cutscene:text("* G-gosh,[wait:5] but then I'd b-be able to hold Susie for safety,[wait:5] a-and...", "blush_smile", "noelle")
        cutscene:showNametag("Susie")
        cutscene:text("* Huh?[wait:10] You said somethin' about me, Noelle?", "surprise", "susie")
        cutscene:showNametag("Noelle")
        event:setSprite("shocked")
        cutscene:text("* H-huh?!", "shock", "noelle")
        event:resetSprite()
        event:setFacing("right")
        cutscene:text("* O-oh, um,[wait:5] n-not at all, Susie,[wait:5] fahahaha!", "blush_big_smile", "noelle")
        cutscene:showNametag("Susie")
        cutscene:text("* If you say so.", "suspicious", "susie")
        cutscene:showNametag("Noelle")
        event:setFacing("down")
        cutscene:text("* ...", "blush_side", "noelle")
        cutscene:showNametag("Hero")
        cutscene:text("* ...", "shocked", "hero")
        cutscene:hideNametag()
    end,

    jammarcy = function(cutscene, event)
        cutscene:showNametag("Marcy")
        cutscene:text("* Marcy can't wait to see what's in the computer lab!", "happy", "marcy")
        cutscene:text("* What if it's a gift just for Marcy?", "happy_closed", "marcy")
        cutscene:showNametag("Jamm")
        cutscene:text("* Settle down, Marcy,[wait:5] we gotta wait for Hero to be ready first.", "look_left", "jamm")
        cutscene:text("* (Also,[wait:5] you're not the only one invited here...)", "look_left", "jamm")
        cutscene:showNametag("Marcy")
        cutscene:text("* Aww...[wait:5] but Marcy wants to go now...", "sad", "marcy")
        cutscene:showNametag("Jamm")
        cutscene:text("* I'm sure they'll be ready soon.", "smile", "jamm")
        cutscene:hideNametag()
    end,

    computer = function(cutscene, event)
        local hero = cutscene:getCharacter("hero_lw")
        local susie = cutscene:getCharacter("susie_lw")
        local noelle = cutscene:getCharacter("noelle_lw")
        local dess = cutscene:getCharacter("dess")
        local ceroba = cutscene:getCharacter("ceroba")
        local brenda = cutscene:getCharacter("brenda_lw")
        local jammarcy = cutscene:getCharacter("jammarcy_light")
        local computer = cutscene:getCharacter("digicomputer")
        cutscene:wait(0.5)
        hero:alert()
        cutscene:wait(0.5)
        Game.world.music:play("deltarune/creepydoor", 1, 1)
        cutscene:showNametag("Hero")
        cutscene:text("* Huh?[wait:10] It's a...[wait:5] computer?", "shocked", "hero")
        cutscene:hideNametag()
        cutscene:walkTo(hero, computer.x - 10, computer.y + 40, 2)
        cutscene:walkTo(susie, susie.x, susie.y - 120, 1)
        cutscene:walkTo(noelle, noelle.x, noelle.y - 120, 1)
        cutscene:walkTo(dess, dess.x, dess.y - 120, 1)
        cutscene:walkTo(ceroba, ceroba.x, ceroba.y - 120, 1)
        cutscene:walkTo(brenda, brenda.x, brenda.y - 120, 1)
        cutscene:walkTo(jammarcy, jammarcy.x, jammarcy.y - 120, 1)
        cutscene:wait(1)
        cutscene:walkTo(susie, 280, 280, 1, "right")
        cutscene:walkTo(noelle, 410, 310, 1, "left")
        cutscene:walkTo(dess, 420, 370, 1, "left")
        cutscene:walkTo(brenda, 350, 390, 1, "up")
        cutscene:walkTo(jammarcy, 260, 340, 1, "right")
        cutscene:walkTo(ceroba, 220, 385, 1, "right")
        cutscene:wait(1)
        cutscene:showNametag("Noelle", {top = true})
        cutscene:text("* I d-don't think I've seen this computer in here before.", "afraid", "noelle", {top = true})
        cutscene:showNametag("Susie", {top = true})
        cutscene:text("* You think the person who called us put it here?", "suspicious", "susie", {top = true})
        cutscene:showNametag("Brenda", {top = true})
        cutscene:text("* Seems likely to me.", "neutral", "brenda_lw", {top = true})
        cutscene:text("* But why would they put it here?", "down", "brenda_lw", {top = true})
        cutscene:showNametag("Dess", {top = true})
        cutscene:text("* oh oh oh maybe they want us to play space pinball", "teehee", "dess", {top = true})
        cutscene:showNametag("Hero", {top = true})
        cutscene:text("* It's not even plugged in,[wait:5] Dess.", "really", "hero", {top = true})
        cutscene:showNametag("Susie", {top = true})
        cutscene:text("* Damnit!", "teeth", "susie", {top = true})
        cutscene:showNametag("Jamm", {top = true})
        cutscene:text("* Susie,[wait:5] please.[wait:10]\n* My daughter is right here.", "stern", "jamm", {top = true})
        cutscene:showNametag("Ceroba", {top = true})
        cutscene:text("* Hmm...[wait:5] All of this is so strange...", "closed_eyes", "ceroba", {top = true})
        cutscene:showNametag("Hero", {top = true})
        cutscene:text("* That's odd...", "annoyed", "hero", {top = true})
        cutscene:text("* Even though it's not plugged in,[wait:5] the lights are still on...", "suspicious", "hero", {top = true})
        cutscene:showNametag("Susie", {top = true})
        cutscene:text("* Maybe you should turn it on then?", "neutral", "susie", {top = true})
        cutscene:showNametag("Hero", {top = true})
        cutscene:text("* It's worth a shot...", "pout", "hero", {top = true})
        cutscene:hideNametag()
        cutscene:wait(0.2)
        Assets.playSound("noise")
        cutscene:wait(3)
        cutscene:showNametag("Hero", {top = true})
        cutscene:text("* ...", "neutral_closed", "hero", {top = true})
        cutscene:hideNametag()
        cutscene:wait(3)
        cutscene:showNametag("Hero", {top = true})
        hero:setFacing("down")
        cutscene:text("[noskip]* Well,[wait:5] I dunno what I was expecti", "annoyed", "hero", {auto = true, top = true})
        cutscene:hideNametag()
        hero:setFacing("up")
        cutscene:slideTo(hero, hero.x, hero.y + 20, 0.5, "out-cubic")
        susie:setSprite("shock_down")
        computer:setSprite("on")
        computer:flash()
        Game.world.music:stop()
        Assets.playSound("great_shine")
        cutscene:wait(2)
        cutscene:showNametag("Hero", {top = true})
        cutscene:text("* ...", "shocked", "hero", {top = true})
        cutscene:showNametag("Susie", {top = true})
        cutscene:text("* ...", "shock", "susie", {top = true})
        susie:resetSprite()
        cutscene:text("* Did...[wait:10] Did it just turn on?", "shock_nervous", "susie", {top = true})
        cutscene:showNametag("Noelle", {top = true})
        cutscene:text("* The screen's so bright,[wait:5] I c-can't see anything on it...", "surprise_frown_b", "noelle", {top = true})
        cutscene:hideNametag()
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        Game.world.music:play("deltarune/deep_noise", 0, 1)
        Game.world.music:fade(1, 1)
        noelle:setSprite("shocked")
        cutscene:wait(1)
        cutscene:showNametag("Noelle", {top = true})
        cutscene:text("* Hey,[wait:5] d-did you guys feel that?", "shock_b", "noelle", {top = true})
        cutscene:hideNametag()
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:showNametag("Hero", {top = true})
        cutscene:text("* I...[wait:5] I can't...", "shocked", "hero", {top = true})
        cutscene:hideNametag()
        susie:setSprite("shock_down")
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:showNametag("Susie", {top = true})
        cutscene:text("* Why can't I move?!", "bangs/nervous_b", "susie", {top = true})
        cutscene:hideNametag()
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:showNametag("Marcy", {top = true})
        cutscene:text("* Papa![wait:10] Marcy's scared!", "surprised", "marcy", {top = true})
        cutscene:hideNametag()
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:showNametag("Jamm", {top = true})
        cutscene:text("* Just keep holding onto me,[wait:5] okay?!", "ouch", "jamm", {top = true})
        cutscene:hideNametag()
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:showNametag("Dess", {top = true})
        cutscene:text("* hm yes i appear to be in immense pain right now", "mspaint", "dess", {top = true})
        cutscene:hideNametag()
        ceroba:setSprite("worried")
        ceroba.flip_x = true
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:showNametag("Ceroba", {top = true})
        cutscene:text("* W-what the hell is going on?!", "confounded", "ceroba", {top = true})
        cutscene:hideNametag()
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:showNametag("Brenda", {top = true})
        cutscene:text("* I DON'T WANNA DIE![wait:5]\n* I DON'T WANNA DIE!![wait:5]\n* I DON'T WANNA DIE!!!", "crying", "brenda_lw", {top = true})
        cutscene:hideNametag()
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:showNametag("Hero", {top = true})
        cutscene:text("[noskip][speed:0.5]* Everything's...[wait:5][speed:0.3]\n* going.....[wait:10][speed:0.15]\n* numb..........", "shade", "hero", {top = true})
        cutscene:hideNametag()
        Game.world:shake(5)
        Assets.playSound("closet_impact")
        cutscene:wait(1)
        cutscene:wait(cutscene:fadeOut(3, {color = {1,1,1}}))
        Game.world.music:fade(0, 1)
        cutscene:wait(2)
        Game:swapIntoMod("dlc_digimon", false)
    end,
}
