return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 16,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 11,
  nextobjectid = 76,
  properties = {
    ["border"] = "dev",
    ["music"] = "dev"
  },
  tilesets = {
    {
      name = "devroom_mono",
      firstgid = 1,
      filename = "../../../../tilesets/devroom_mono.tsx",
      exportfilename = "../../../../tilesets/devroom_mono.lua"
    },
    {
      name = "devroom_objects",
      firstgid = 145,
      filename = "../../../../tilesets/devroom_objects.tsx",
      exportfilename = "../../../../tilesets/devroom_objects.lua"
    },
    {
      name = "cctiles",
      firstgid = 149,
      filename = "../../../../tilesets/cctiles.tsx",
      exportfilename = "../../../../tilesets/cctiles.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 24,
      height = 16,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        17, 17, 17, 17, 37, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 38, 17, 17, 17,
        17, 17, 17, 37, 102, 53, 53, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 53, 53, 100, 38, 17, 17,
        17, 17, 37, 102, 114, 41, 41, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 41, 41, 112, 100, 38, 17,
        17, 17, 18, 114, 0, 53, 53, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 53, 53, 53, 0, 52, 16, 17,
        29, 29, 30, 0, 0, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 0, 52, 16, 17,
        53, 53, 54, 0, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 52, 16, 17,
        41, 41, 54, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 16, 17,
        53, 53, 54, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 14, 16, 17,
        65, 65, 66, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 14, 16, 17,
        86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 14, 16, 17,
        14, 14, 14, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 14, 16, 17,
        5, 5, 6, 14, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 14, 16, 17,
        17, 17, 18, 14, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 14, 16, 17,
        17, 17, 49, 6, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 86, 86, 14, 4, 50, 17,
        17, 17, 17, 49, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 86, 86, 4, 50, 17, 17,
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 86, 86, 16, 17, 17, 17
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 24,
      height = 16,
      id = 2,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 114, 0, 0, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 0, 0, 112, 112, 0, 0,
        0, 0, 0, 114, 126, 0, 0, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 35, 0, 0, 124, 112, 0, 0,
        0, 0, 0, 126, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 124, 0, 0,
        0, 0, 0, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 560,
          width = 560,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 520,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 440,
          width = 120,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 240,
          width = 120,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 120,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 80,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 160,
          width = 600,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 80,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 120,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 280,
          width = 40,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 520,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 560,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 480,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 360,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 240,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 290,
          y = 420,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 290,
          y = 290,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 610,
          y = 420,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 610,
          y = 290,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 16,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 640,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "floor2/dev/main_1",
            ["marker"] = "party"
          }
        },
        {
          id = 17,
          name = "dogconegroup",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["default_state"] = true
          }
        },
        {
          id = 18,
          name = "dogconegroup",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["default_state"] = true
          }
        },
        {
          id = 19,
          name = "jukebox",
          type = "",
          shape = "point",
          x = 740,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 200,
          width = 62,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "partyroom.party",
            ["once"] = false,
            ["solid"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects_tables",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 330,
          width = 100,
          height = 70,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 330,
          width = 100,
          height = 70,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 460,
          width = 100,
          height = 70,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 460,
          width = 100,
          height = 70,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 280,
          width = 100,
          height = 70,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 400,
          width = 100,
          height = 70,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 520,
          width = 100,
          height = 70,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "npc",
          type = "",
          shape = "point",
          x = 145,
          y = 330,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "susie",
            ["cutscene"] = "partyroom.susie",
            ["sprite"] = "wall_right"
          }
        },
        {
          id = 64,
          name = "npc",
          type = "",
          shape = "point",
          x = 330,
          y = 420,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "hero",
            ["cutscene"] = "partyroom.hero",
            ["facing"] = "down"
          }
        },
        {
          id = 68,
          name = "npc",
          type = "",
          shape = "point",
          x = 690,
          y = 224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "dess",
            ["cutscene"] = "partyroom.dess",
            ["facing"] = "down"
          }
        },
        {
          id = 69,
          name = "npc",
          type = "",
          shape = "point",
          x = 464,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "noelle",
            ["cutscene"] = "partyroom.noelle",
            ["facing"] = "down"
          }
        },
        {
          id = 71,
          name = "npc",
          type = "",
          shape = "point",
          x = 304,
          y = 290,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "kris",
            ["cutscene"] = "partyroom.kris",
            ["facing"] = "down"
          }
        },
        {
          id = 73,
          name = "npc",
          type = "",
          shape = "point",
          x = 624,
          y = 290,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "mario",
            ["cutscene"] = "partyroom.mario",
            ["facing"] = "down"
          }
        },
        {
          id = 74,
          name = "npc",
          type = "",
          shape = "point",
          x = 676,
          y = 290,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "pauling",
            ["cutscene"] = "partyroom.pauling",
            ["facing"] = "down"
          }
        },
        {
          id = 75,
          name = "npc",
          type = "",
          shape = "point",
          x = 830,
          y = 500,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "ostarwalker",
            ["cutscene"] = "partyroom.ostarwalker",
            ["sprite"] = "base"
          }
        },
        {
          id = 70,
          name = "npc",
          type = "",
          shape = "point",
          x = 516,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "berdly",
            ["cutscene"] = "partyroom.berdly",
            ["facing"] = "down"
          }
        },
        {
          id = 72,
          name = "npc",
          type = "",
          shape = "point",
          x = 356,
          y = 290,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "ralsei",
            ["cutscene"] = "partyroom.ralsei",
            ["facing"] = "down"
          }
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 220,
          width = 62,
          height = 104,
          rotation = 0,
          gid = 148,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "main",
          type = "",
          shape = "point",
          x = 760,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "spawn",
          type = "",
          shape = "point",
          x = 760,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
