return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 45,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 9,
  nextobjectid = 80,
  properties = {
    ["border"] = "titan",
    ["music"] = "topfloor",
    ["serious"] = true
  },
  tilesets = {
    {
      name = "topfloor",
      firstgid = 1,
      filename = "../../tilesets/topfloor.tsx"
    },
    {
      name = "topfloor_objects",
      firstgid = 37,
      filename = "../../tilesets/topfloor_objects.tsx",
      exportfilename = "../../tilesets/topfloor_objects.lua"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects_bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 6,
          name = "topfloor_bg",
          type = "",
          shape = "point",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 45,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 2, 20, 7,
        8, 8, 8, 28, 8, 8, 8, 8, 29, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 28, 8, 8, 8, 29, 8, 8, 8, 8, 8, 8, 8, 8, 28, 8, 8, 8, 8, 30, 8, 8, 29, 8, 7,
        8, 30, 8, 4, 5, 6, 8, 4, 5, 6, 8, 4, 5, 6, 28, 4, 5, 6, 8, 4, 5, 6, 8, 4, 5, 6, 8, 4, 5, 6, 29, 4, 5, 6, 8, 4, 5, 6, 8, 4, 5, 6, 8, 8, 7,
        8, 8, 8, 10, 11, 12, 8, 10, 11, 12, 30, 10, 11, 12, 8, 10, 11, 12, 8, 10, 11, 12, 8, 10, 11, 12, 30, 10, 11, 12, 8, 10, 11, 12, 8, 10, 11, 12, 8, 10, 11, 12, 8, 8, 7,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 7,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 7,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 7,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 7,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 26, 26, 26, 26, 32, 33, 7,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 25, 26, 26, 27, 26, 26, 7,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 25, 26, 26, 27, 26, 26, 7
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 45,
      height = 12,
      id = 3,
      name = "decal",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 400,
          width = 1520,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1680,
          y = 400,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1760,
          y = 240,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 200,
          width = 1760,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects_window_floor",
      class = "",
      visible = true,
      opacity = 0.2,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 0, 255 },
      properties = {},
      objects = {
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 130,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 290,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 610,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 770,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 930,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1090,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1250,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1410,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1570,
          y = 360,
          width = 100,
          height = 120,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 130,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 290,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 610,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 770,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 930,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1090,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1250,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1410,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1570,
          y = 400,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects_window_wall",
      class = "",
      visible = true,
      opacity = 0.3,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 0, 255 },
      properties = {},
      objects = {
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 130,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 290,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 610,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 770,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 930,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1090,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1250,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1410,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1570,
          y = 200,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 130,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 290,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 610,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 770,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 930,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1090,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1250,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1410,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1570,
          y = 240,
          width = 100,
          height = 40,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 240,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "topfloor/ambush",
            ["marker"] = "east2"
          }
        },
        {
          id = 8,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1520,
          y = 480,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 150,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 470,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 630,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 1270,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 950,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 790,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 1430,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "topfloor_windoweye",
          type = "",
          shape = "rectangle",
          x = 1590,
          y = 150,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "voidenemy",
          type = "",
          shape = "point",
          x = 1140,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "voidspawn",
            ["chase"] = true,
            ["chaseaccel"] = 1.075,
            ["chasemax"] = 100,
            ["chasespeed"] = 2,
            ["chasetype"] = "multiplier",
            ["encounter"] = "voidspawn",
            ["once"] = true
          }
        },
        {
          id = 19,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 110,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 270,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 430,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 590,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 750,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 910,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 1070,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 1230,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 1390,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "topfloor_highlight",
          type = "",
          shape = "rectangle",
          x = 1550,
          y = 240,
          width = 140,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "topfloor_windowdraw",
          type = "",
          shape = "point",
          x = 40,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "dogconegroup",
          type = "",
          shape = "rectangle",
          x = 1520,
          y = 440,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["default_state"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 76,
          name = "west",
          type = "",
          shape = "point",
          x = 40,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "spawn",
          type = "",
          shape = "point",
          x = 110,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "north",
          type = "",
          shape = "point",
          x = 1600,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
