return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 22,
  height = 22,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 14,
  nextobjectid = 15,
  properties = {},
  tilesets = {
    {
      name = "hell",
      firstgid = 1,
      filename = "../../../tilesets/hell.tsx",
      exportfilename = "../../../tilesets/hell.lua"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "objects_bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "goner_bg",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/world/bg/temple_back.png",
      id = 8,
      name = "temple_back",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 244,
      offsety = 252,
      parallaxx = 0.82,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/world/bg/field.png",
      id = 7,
      name = "field",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 256,
      parallaxx = 0.86,
      parallaxy = 1,
      repeatx = true,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/world/bg/temple_middle.png",
      id = 6,
      name = "temple_middle",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 178,
      parallaxx = 0.9,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/world/bg/temple_front.png",
      id = 5,
      name = "temple_front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 710,
      offsety = 134,
      parallaxx = 0.95,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/world/bg/tower.png",
      id = 4,
      name = "tower",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 230,
      offsety = 0,
      parallaxx = 0.96,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/world/bg/gradient.png",
      id = 3,
      name = "gradient",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 350,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "objects_clock",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 16,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 9,
          name = "fl_clocks",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["flip"] = true
          }
        },
        {
          id = 10,
          name = "fl_clocks",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 520,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "fl_clocks",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["flip"] = true
          }
        },
        {
          id = 12,
          name = "fl_clocks",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "fl_clocks",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "fl_clocks",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["flip"] = true
          }
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 22,
      height = 22,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 5, 19, 19, 19, 19,
        11, 11, 11, 11, 11, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 12, 26, 27, 26, 27,
        19, 19, 19, 19, 6, 11, 13, 3, 3, 3, 3, 3, 3, 3, 3, 3, 14, 12, 34, 35, 34, 35,
        26, 27, 26, 27, 10, 11, 5, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 34, 35, 34, 35,
        34, 35, 34, 35, 10, 11, 12, 26, 27, 26, 27, 26, 27, 26, 27, 26, 27, 28, 34, 35, 34, 35,
        34, 35, 34, 35, 10, 11, 12, 34, 35, 34, 35, 34, 35, 34, 35, 34, 35, 36, 34, 35, 34, 35,
        34, 35, 34, 35, 10, 11, 12, 34, 35, 34, 35, 34, 35, 34, 35, 34, 35, 36, 34, 35, 34, 35,
        34, 35, 34, 35, 10, 11, 12, 34, 35, 34, 35, 34, 35, 34, 35, 34, 35, 36, 34, 35, 34, 35,
        34, 35, 34, 35, 10, 11, 12, 34, 35, 34, 35, 34, 35, 34, 35, 34, 35, 36, 34, 35, 34, 35,
        34, 35, 34, 35, 10, 11, 12, 34, 35, 34, 35, 34, 35, 34, 35, 34, 35, 36, 34, 35, 34, 35
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 440,
          width = 280,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 440,
          width = 360,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 400,
          width = 240,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 520,
          width = 160,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 640,
          width = 440,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 600,
          width = 160,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 8,
          name = "spawn",
          type = "",
          shape = "point",
          x = 40,
          y = 560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
