return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 21,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 22,
  nextobjectid = 134,
  properties = {
    ["border"] = "leaves",
    ["light"] = true,
    ["music"] = "hometown"
  },
  tilesets = {
    {
      name = "hometown",
      firstgid = 1,
      filename = "../../../../tilesets/hometown.tsx",
      exportfilename = "../../../../tilesets/hometown.lua"
    },
    {
      name = "hometownobjects",
      firstgid = 287,
      filename = "../../../../tilesets/hometownobjects.tsx",
      exportfilename = "../../../../tilesets/hometownobjects.lua"
    },
    {
      name = "hometownshadowsobjects",
      firstgid = 441,
      filename = "../../../../tilesets/hometownshadowsobjects.tsx",
      exportfilename = "../../../../tilesets/hometownshadowsobjects.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 21,
      id = 1,
      name = "tile",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57,
        57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57,
        57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57,
        57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57,
        57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57,
        57, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 57, 57, 57, 57,
        57, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 61, 57, 57, 57, 57,
        57, 41, 58, 58, 58, 58, 58, 58, 58, 58, 58, 61, 58, 58, 58, 57,
        57, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 61, 58, 58, 58, 57,
        57, 41, 58, 58, 58, 58, 58, 58, 58, 58, 58, 61, 58, 58, 58, 57,
        57, 58, 58, 58, 41, 58, 58, 58, 58, 58, 58, 61, 58, 58, 58, 57,
        57, 58, 40, 41, 58, 58, 41, 71, 71, 71, 71, 72, 58, 58, 58, 57,
        57, 58, 58, 58, 40, 58, 61, 57, 58, 58, 58, 58, 58, 58, 58, 57,
        57, 58, 58, 58, 58, 58, 61, 58, 58, 58, 58, 58, 58, 58, 58, 57,
        57, 58, 58, 58, 58, 58, 72, 58, 58, 58, 58, 58, 58, 58, 57, 57,
        57, 57, 57, 57, 57, 57, 57, 13, 13, 13, 57, 48, 49, 49, 49, 57,
        57, 57, 57, 57, 57, 57, 58, 13, 13, 13, 58, 57, 57, 57, 57, 57,
        57, 57, 57, 57, 57, 57, 58, 13, 13, 13, 58, 57, 57, 57, 57, 57,
        57, 57, 57, 57, 57, 57, 58, 13, 13, 13, 58, 57, 57, 57, 57, 57,
        57, 57, 57, 57, 57, 57, 58, 13, 13, 13, 58, 57, 57, 57, 57, 57,
        57, 57, 57, 57, 57, 57, 58, 13, 13, 13, 58, 57, 57, 57, 57, 57
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 21,
      id = 3,
      name = "tile2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        173, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 172,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 257, 258, 259, 0,
        0, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 268, 269, 270, 0,
        0, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 268, 269, 270, 0,
        0, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 268, 269, 270, 0,
        0, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 268, 269, 270, 0,
        0, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 268, 269, 270, 0,
        0, 69, 0, 0, 0, 0, 0, 257, 258, 258, 258, 258, 269, 269, 270, 0,
        0, 69, 0, 0, 0, 0, 0, 268, 269, 269, 269, 269, 269, 269, 270, 0,
        0, 0, 46, 46, 46, 46, 0, 268, 269, 269, 280, 280, 280, 280, 281, 0,
        0, 0, 0, 0, 0, 0, 98, 0, 0, 0, 98, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 15, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 15, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 15, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 15, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 15, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 21,
      id = 4,
      name = "tree",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151,
        151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150,
        150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151,
        163, 162, 145, 146, 0, 0, 0, 0, 0, 0, 146, 145, 146, 147, 146, 161,
        153, 173, 156, 157, 0, 0, 0, 0, 0, 0, 157, 156, 157, 158, 157, 93,
        153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        151, 150, 151, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93,
        150, 151, 150, 151, 150, 153, 0, 0, 0, 0, 0, 138, 141, 140, 180, 190,
        151, 150, 151, 150, 150, 153, 0, 0, 0, 0, 0, 149, 150, 151, 152, 151,
        150, 151, 150, 151, 150, 153, 0, 0, 0, 0, 0, 149, 151, 150, 151, 152,
        151, 150, 151, 150, 150, 153, 0, 0, 0, 0, 0, 149, 150, 151, 152, 151,
        150, 151, 150, 151, 150, 153, 0, 0, 0, 0, 0, 149, 151, 150, 151, 152,
        151, 150, 151, 150, 150, 153, 0, 0, 0, 0, 0, 149, 150, 151, 150, 151
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "objects_grass",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 454,
          y = 410,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 69,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 414,
          y = 410,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 374,
          y = 410,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 410,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 296,
          y = 410,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 410,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 410,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 396,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 396,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 396,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 396,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 458,
          y = 388,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 69,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 458,
          y = 350,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 69,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 458,
          y = 310,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 69,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 456,
          y = 276,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 69,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 52,
          y = 368,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 52,
          y = 338,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 52,
          y = 316,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 52,
          y = 276,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          gid = 67,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/maps/hometown/krishouse.png",
      id = 9,
      name = "house",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 80,
      offsety = 40,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 91,
          y = 200,
          width = 520,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 200,
          width = 40,
          height = 400,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 600,
          width = 200,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 640,
          width = 40,
          height = 200,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 600,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 600,
          width = 160,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 200,
          width = 40,
          height = 440,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "polygon",
          x = 160,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -120, y = -80 },
            { x = -120, y = 0 }
          },
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 348,
          width = 92,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 92,
          y = 334,
          width = 124,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 92,
          y = 240,
          width = 40,
          height = 94,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 348,
          width = 90,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 418,
          y = 240,
          width = 40,
          height = 108,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "objects_light_night",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 250,
          y = 342,
          width = 26,
          height = 30,
          rotation = 0,
          opacity = 1,
          gid = 356,
          visible = true,
          properties = {
            ["night"] = 2
          }
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 398,
          y = 342,
          width = 26,
          height = 30,
          rotation = 0,
          opacity = 1,
          gid = 356,
          visible = true,
          properties = {
            ["night"] = 2
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 10,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 840,
          width = 200,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "light/hometown/town_north",
            ["marker"] = "spawn"
          }
        },
        {
          id = 11,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 308,
          y = 346,
          width = 60,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["exit_delay"] = 1,
            ["exit_sound"] = "doorclose",
            ["facing"] = "left",
            ["map"] = "light/hometown/torielhouse/tor_house",
            ["marker"] = "entryeast",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 19,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 200,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "hometown.secret_path",
            ["once"] = false
          }
        },
        {
          id = 22,
          name = "torcar",
          type = "",
          shape = "rectangle",
          x = 460,
          y = 220,
          width = 156,
          height = 148,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 9,
          name = "spawn",
          type = "",
          shape = "point",
          x = 340,
          y = 800,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "entryhouse",
          type = "",
          shape = "point",
          x = 337,
          y = 420,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "entry_secret",
          type = "",
          shape = "point",
          x = 66,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 21,
      id = 6,
      name = "treeup",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 194, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 192, 180, 181, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 192, 180, 181, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/maps/hometown/krishouseover.png",
      id = 10,
      name = "houseover",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 80,
      offsety = 40,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "objects_light_above_night",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 16,
      name = "shadows",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 15,
          name = "objects_shadows_evening_cutout",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 19,
          name = "objects_shadows_morning_cutout",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 81,
              name = "",
              type = "",
              shape = "rectangle",
              x = 440,
              y = 820,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 82,
              name = "",
              type = "",
              shape = "rectangle",
              x = 440,
              y = 860,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 83,
              name = "",
              type = "",
              shape = "rectangle",
              x = 440,
              y = 740,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 84,
              name = "",
              type = "",
              shape = "rectangle",
              x = 440,
              y = 780,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 85,
              name = "",
              type = "",
              shape = "rectangle",
              x = 440,
              y = 700,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 86,
              name = "",
              type = "",
              shape = "rectangle",
              x = 444,
              y = 722,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 488,
              visible = true,
              properties = {}
            },
            {
              id = 88,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 580,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 89,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 620,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 90,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 500,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 91,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 540,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 93,
              name = "",
              type = "",
              shape = "rectangle",
              x = 524,
              y = 732,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 488,
              visible = true,
              properties = {}
            },
            {
              id = 95,
              name = "",
              type = "",
              shape = "rectangle",
              x = 588,
              y = 730,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 488,
              visible = true,
              properties = {}
            },
            {
              id = 96,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 420,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 97,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 460,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 98,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 340,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 99,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 380,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 100,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 260,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 101,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 300,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 102,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 180,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 103,
              name = "",
              type = "",
              shape = "rectangle",
              x = 600,
              y = 220,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 485,
              visible = true,
              properties = {}
            },
            {
              id = 104,
              name = "",
              type = "",
              shape = "rectangle",
              x = 564,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 488,
              visible = true,
              properties = {}
            },
            {
              id = 105,
              name = "",
              type = "",
              shape = "rectangle",
              x = 8,
              y = 200,
              width = 606,
              height = 66,
              rotation = 0,
              opacity = 1,
              gid = 475,
              visible = true,
              properties = {}
            },
            {
              id = 107,
              name = "",
              type = "",
              shape = "rectangle",
              x = 44,
              y = 640,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 488,
              visible = true,
              properties = {}
            },
            {
              id = 108,
              name = "",
              type = "",
              shape = "rectangle",
              x = 124,
              y = 680,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 488,
              visible = true,
              properties = {}
            },
            {
              id = 109,
              name = "",
              type = "",
              shape = "rectangle",
              x = 194,
              y = 708,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 477,
              visible = true,
              properties = {}
            },
            {
              id = 110,
              name = "",
              type = "",
              shape = "rectangle",
              x = 194,
              y = 668,
              width = 40,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 477,
              visible = true,
              properties = {}
            },
            {
              id = 111,
              name = "",
              type = "",
              shape = "rectangle",
              x = 10,
              y = 580,
              width = 32,
              height = 96,
              rotation = 0,
              opacity = 1,
              gid = 486,
              visible = true,
              properties = {}
            },
            {
              id = 112,
              name = "",
              type = "",
              shape = "rectangle",
              x = 30,
              y = 640,
              width = 32,
              height = 92,
              rotation = 0,
              opacity = 1,
              gid = 486,
              visible = true,
              properties = {}
            },
            {
              id = 113,
              name = "",
              type = "",
              shape = "rectangle",
              x = 10,
              y = 680,
              width = 190,
              height = 112,
              rotation = 0,
              opacity = 1,
              gid = 486,
              visible = true,
              properties = {}
            },
            {
              id = 115,
              name = "",
              type = "",
              shape = "rectangle",
              x = 98,
              y = 578,
              width = 120,
              height = 18,
              rotation = 0,
              opacity = 1,
              gid = 491,
              visible = true,
              properties = {}
            },
            {
              id = 92,
              name = "",
              type = "",
              shape = "rectangle",
              x = 32,
              y = 660,
              width = 576,
              height = 178,
              rotation = 0,
              opacity = 1,
              gid = 476,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 21,
          name = "objects_shadows_evening",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 20,
          name = "objects_shadows_morning",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 54,
              name = "",
              type = "",
              shape = "rectangle",
              x = 80,
              y = 420,
              width = 390,
              height = 380,
              rotation = 0,
              opacity = 1,
              gid = 496,
              visible = true,
              properties = {}
            },
            {
              id = 55,
              name = "",
              type = "",
              shape = "rectangle",
              x = 132,
              y = 400,
              width = 385,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 56,
              name = "",
              type = "",
              shape = "rectangle",
              x = 449,
              y = 731,
              width = 64,
              height = 506.622,
              rotation = -45,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 57,
              name = "",
              type = "",
              shape = "rectangle",
              x = 200,
              y = 472,
              width = 180,
              height = 96,
              rotation = 0,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 59,
              name = "",
              type = "",
              shape = "rectangle",
              x = 354,
              y = 622,
              width = 180,
              height = 166,
              rotation = -36.6376,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 60,
              name = "",
              type = "",
              shape = "rectangle",
              x = 390,
              y = 620,
              width = 250,
              height = 220,
              rotation = 0,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 61,
              name = "",
              type = "",
              shape = "rectangle",
              x = 317.5,
              y = 785.5,
              width = 62.5685,
              height = 199.738,
              rotation = -45,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 64,
              name = "",
              type = "",
              shape = "rectangle",
              x = 406,
              y = 812,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 508,
              visible = true,
              properties = {}
            },
            {
              id = 65,
              name = "",
              type = "",
              shape = "rectangle",
              x = 240,
              y = 844,
              width = 154,
              height = 140,
              rotation = 0,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 66,
              name = "",
              type = "",
              shape = "rectangle",
              x = 40,
              y = 550,
              width = 100,
              height = 370,
              rotation = 0,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 67,
              name = "",
              type = "",
              shape = "rectangle",
              x = 164,
              y = 558,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 508,
              visible = true,
              properties = {}
            },
            {
              id = 68,
              name = "",
              type = "",
              shape = "rectangle",
              x = 164,
              y = 480,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 508,
              visible = true,
              properties = {}
            },
            {
              id = 69,
              name = "",
              type = "",
              shape = "rectangle",
              x = 402,
              y = 680,
              width = 80,
              height = 24,
              rotation = 180,
              opacity = 1,
              gid = 2147484156,
              visible = true,
              properties = {}
            },
            {
              id = 70,
              name = "",
              type = "",
              shape = "rectangle",
              x = 416,
              y = 772,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 508,
              visible = true,
              properties = {}
            },
            {
              id = 71,
              name = "",
              type = "",
              shape = "rectangle",
              x = 406,
              y = 898,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 508,
              visible = true,
              properties = {}
            },
            {
              id = 75,
              name = "",
              type = "",
              shape = "rectangle",
              x = 460,
              y = 400,
              width = 180,
              height = 230,
              rotation = 0,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 77,
              name = "",
              type = "",
              shape = "rectangle",
              x = 448,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 497,
              visible = true,
              properties = {}
            },
            {
              id = 78,
              name = "",
              type = "",
              shape = "rectangle",
              x = 528,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 497,
              visible = true,
              properties = {}
            },
            {
              id = 79,
              name = "",
              type = "",
              shape = "rectangle",
              x = 400,
              y = 650,
              width = 80,
              height = 60,
              rotation = 0,
              opacity = 1,
              gid = 500,
              visible = true,
              properties = {}
            },
            {
              id = 80,
              name = "",
              type = "",
              shape = "rectangle",
              x = 10,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 497,
              visible = true,
              properties = {}
            },
            {
              id = 117,
              name = "",
              type = "",
              shape = "rectangle",
              x = 226,
              y = 820,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 118,
              name = "",
              type = "",
              shape = "rectangle",
              x = 226,
              y = 860,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 119,
              name = "",
              type = "",
              shape = "rectangle",
              x = 226,
              y = 780,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 120,
              name = "",
              type = "",
              shape = "rectangle",
              x = 226,
              y = 740,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 121,
              name = "",
              type = "",
              shape = "rectangle",
              x = 226,
              y = 700,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 122,
              name = "",
              type = "",
              shape = "rectangle",
              x = 26,
              y = 460,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 123,
              name = "",
              type = "",
              shape = "rectangle",
              x = 26,
              y = 500,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 124,
              name = "",
              type = "",
              shape = "rectangle",
              x = 26,
              y = 420,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 125,
              name = "",
              type = "",
              shape = "rectangle",
              x = 26,
              y = 380,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 126,
              name = "",
              type = "",
              shape = "rectangle",
              x = 26,
              y = 340,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 127,
              name = "",
              type = "",
              shape = "rectangle",
              x = 26,
              y = 300,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 128,
              name = "",
              type = "",
              shape = "rectangle",
              x = 26,
              y = 260,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            },
            {
              id = 129,
              name = "",
              type = "",
              shape = "rectangle",
              x = 26,
              y = 220,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 503,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 21,
          id = 17,
          name = "tiles_shadows_evening",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 21,
          id = 18,
          name = "tiles_shadows_morning",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "objects_overlay",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 23,
          name = "hometowndaynight",
          type = "",
          shape = "point",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
