return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 25,
  nextobjectid = 102,
  properties = {
    ["border"] = "leaves",
    ["light"] = true,
    ["music"] = "hometown"
  },
  tilesets = {
    {
      name = "hometown",
      firstgid = 1,
      filename = "../../../../tilesets/hometown.tsx",
      exportfilename = "../../../../tilesets/hometown.lua"
    },
    {
      name = "hometownobjects",
      firstgid = 287,
      filename = "../../../../tilesets/hometownobjects.tsx",
      exportfilename = "../../../../tilesets/hometownobjects.lua"
    },
    {
      name = "hometownshadowsobjects",
      firstgid = 472,
      filename = "../../../../tilesets/hometownshadowsobjects.tsx",
      exportfilename = "../../../../tilesets/hometownshadowsobjects.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/maps/hometown/room_beach.png",
      id = 7,
      name = "shore",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 12,
      id = 1,
      name = "tile",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 197, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 197, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 197, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 197, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 207, 208, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 227, 217, 218, 219, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        266, 238, 224, 266, 266, 236, 266, 266, 224, 266, 225, 266, 266, 236, 266, 224, 266, 228, 229, 230, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        225, 266, 266, 266, 236, 224, 266, 238, 266, 225, 266, 266, 224, 266, 266, 238, 266, 239, 240, 241, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        249, 249, 248, 249, 249, 249, 249, 249, 249, 249, 249, 248, 249, 249, 249, 249, 249, 250, 251, 252, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        206, 206, 206, 206, 206, 206, 206, 206, 206, 206, 206, 206, 206, 206, 206, 206, 206, 197, 197, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197, 197, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197, 197, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 12,
      id = 2,
      name = "tree",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        161, 162, 163, 162, 161, 162, 163, 162, 161, 162, 163, 162, 161, 162, 163, 162, 161, 162, 163, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        172, 173, 174, 173, 172, 173, 174, 173, 172, 173, 174, 173, 172, 173, 174, 173, 172, 173, 174, 175, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 151, 150, 153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "group",
      id = 16,
      name = "shadows",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 24,
          name = "objects_shadows_evening_topcutout",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 23,
          name = "objects_shadows_morning_topcutout",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 72,
              name = "",
              type = "",
              shape = "rectangle",
              x = -36,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 73,
              name = "",
              type = "",
              shape = "rectangle",
              x = 44,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 74,
              name = "",
              type = "",
              shape = "rectangle",
              x = 124,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 75,
              name = "",
              type = "",
              shape = "rectangle",
              x = 204,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 76,
              name = "",
              type = "",
              shape = "rectangle",
              x = 284,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 77,
              name = "",
              type = "",
              shape = "rectangle",
              x = 364,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 78,
              name = "",
              type = "",
              shape = "rectangle",
              x = 444,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 79,
              name = "",
              type = "",
              shape = "rectangle",
              x = 524,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 80,
              name = "",
              type = "",
              shape = "rectangle",
              x = 604,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 81,
              name = "",
              type = "",
              shape = "rectangle",
              x = 684,
              y = 482,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 38,
              name = "",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 388,
              width = 134,
              height = 90,
              rotation = 0,
              opacity = 1,
              gid = 329,
              visible = true,
              properties = {}
            },
            {
              id = 39,
              name = "",
              type = "",
              shape = "rectangle",
              x = 160,
              y = 388,
              width = 134,
              height = 90,
              rotation = 0,
              opacity = 1,
              gid = 329,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 19,
          name = "objects_shadows_evening_cutout",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 20,
          name = "objects_shadows_morning_cutout",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 56,
              name = "",
              type = "",
              shape = "rectangle",
              x = -36,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 57,
              name = "",
              type = "",
              shape = "rectangle",
              x = 44,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 58,
              name = "",
              type = "",
              shape = "rectangle",
              x = 124,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 59,
              name = "",
              type = "",
              shape = "rectangle",
              x = 204,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 60,
              name = "",
              type = "",
              shape = "rectangle",
              x = 284,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 61,
              name = "",
              type = "",
              shape = "rectangle",
              x = 364,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 62,
              name = "",
              type = "",
              shape = "rectangle",
              x = 444,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 63,
              name = "",
              type = "",
              shape = "rectangle",
              x = 524,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 64,
              name = "",
              type = "",
              shape = "rectangle",
              x = 604,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 65,
              name = "",
              type = "",
              shape = "rectangle",
              x = 684,
              y = 200,
              width = 110,
              height = 120,
              rotation = 0,
              opacity = 1,
              gid = 519,
              visible = true,
              properties = {}
            },
            {
              id = 82,
              name = "",
              type = "",
              shape = "rectangle",
              x = 0,
              y = 480,
              width = 770,
              height = 52,
              rotation = 0,
              opacity = 1,
              gid = 517,
              visible = true,
              properties = {}
            },
            {
              id = 87,
              name = "",
              type = "",
              shape = "rectangle",
              x = 680,
              y = 480,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 509,
              visible = true,
              properties = {}
            },
            {
              id = 88,
              name = "",
              type = "",
              shape = "rectangle",
              x = 680,
              y = 440,
              width = 120,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 509,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 22,
          name = "objects_shadows_evening",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 21,
          name = "objects_shadows_morning",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 44,
              name = "",
              type = "",
              shape = "rectangle",
              x = 8,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 45,
              name = "",
              type = "",
              shape = "rectangle",
              x = -72,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 46,
              name = "",
              type = "",
              shape = "rectangle",
              x = 168,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 47,
              name = "",
              type = "",
              shape = "rectangle",
              x = 88,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 48,
              name = "",
              type = "",
              shape = "rectangle",
              x = 328,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 49,
              name = "",
              type = "",
              shape = "rectangle",
              x = 248,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 50,
              name = "",
              type = "",
              shape = "rectangle",
              x = 488,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 51,
              name = "",
              type = "",
              shape = "rectangle",
              x = 408,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 52,
              name = "",
              type = "",
              shape = "rectangle",
              x = 648,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 53,
              name = "",
              type = "",
              shape = "rectangle",
              x = 568,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 55,
              name = "",
              type = "",
              shape = "rectangle",
              x = 728,
              y = 180,
              width = 80,
              height = 46,
              rotation = 0,
              opacity = 1,
              gid = 528,
              visible = true,
              properties = {}
            },
            {
              id = 83,
              name = "",
              type = "",
              shape = "rectangle",
              x = 735,
              y = 445,
              width = 120.208,
              height = 69.4975,
              rotation = 45,
              opacity = 1,
              gid = 531,
              visible = true,
              properties = {}
            },
            {
              id = 31,
              name = "",
              type = "",
              shape = "rectangle",
              x = 480,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 32,
              name = "",
              type = "",
              shape = "rectangle",
              x = 560,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 33,
              name = "",
              type = "",
              shape = "rectangle",
              x = 640,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 34,
              name = "",
              type = "",
              shape = "rectangle",
              x = 720,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 35,
              name = "",
              type = "",
              shape = "rectangle",
              x = 240,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 36,
              name = "",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 37,
              name = "",
              type = "",
              shape = "rectangle",
              x = 400,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 40,
              name = "",
              type = "",
              shape = "rectangle",
              x = 160,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 42,
              name = "",
              type = "",
              shape = "rectangle",
              x = 0,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 43,
              name = "",
              type = "",
              shape = "rectangle",
              x = 80,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 67,
              name = "",
              type = "",
              shape = "rectangle",
              x = 786,
              y = 140,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 534,
              visible = true,
              properties = {}
            },
            {
              id = 68,
              name = "",
              type = "",
              shape = "rectangle",
              x = 786,
              y = 100,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 534,
              visible = true,
              properties = {}
            },
            {
              id = 69,
              name = "",
              type = "",
              shape = "rectangle",
              x = 786,
              y = 60,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 534,
              visible = true,
              properties = {}
            },
            {
              id = 70,
              name = "",
              type = "",
              shape = "rectangle",
              x = 786,
              y = 20,
              width = 14,
              height = 40,
              rotation = 0,
              opacity = 1,
              gid = 534,
              visible = true,
              properties = {}
            },
            {
              id = 71,
              name = "",
              type = "",
              shape = "rectangle",
              x = 800,
              y = 280,
              width = 160,
              height = 280,
              rotation = 0,
              opacity = 1,
              gid = 531,
              visible = true,
              properties = {}
            },
            {
              id = 85,
              name = "",
              type = "",
              shape = "rectangle",
              x = 893,
              y = 475,
              width = 80,
              height = 24,
              rotation = 225,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 86,
              name = "",
              type = "",
              shape = "rectangle",
              x = 860,
              y = 440,
              width = 80,
              height = 24,
              rotation = 225,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 89,
              name = "",
              type = "",
              shape = "rectangle",
              x = 800,
              y = 304,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 90,
              name = "",
              type = "",
              shape = "rectangle",
              x = 878,
              y = 302,
              width = 80,
              height = 24,
              rotation = 0,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 95,
              name = "",
              type = "",
              shape = "rectangle",
              x = 982,
              y = 280,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 96,
              name = "",
              type = "",
              shape = "rectangle",
              x = 984,
              y = 200,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 97,
              name = "",
              type = "",
              shape = "rectangle",
              x = 984,
              y = 120,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 98,
              name = "",
              type = "",
              shape = "rectangle",
              x = 984,
              y = 40,
              width = 80,
              height = 24,
              rotation = -90,
              opacity = 1,
              gid = 539,
              visible = true,
              properties = {}
            },
            {
              id = 101,
              name = "",
              type = "",
              shape = "rectangle",
              x = 0,
              y = 280,
              width = 800,
              height = 100,
              rotation = 0,
              opacity = 1,
              gid = 531,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 30,
          height = 12,
          id = 18,
          name = "tiles_shadows_evening",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 30,
          height = 12,
          id = 17,
          name = "tiles_shadows_morning",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 0,
          width = 40,
          height = 480,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 800,
          height = 200,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 400,
          width = 800,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 134,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 134,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 200,
          width = 40,
          height = 200,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["facing"] = "left",
            ["map"] = "light/hometown/town_north",
            ["marker"] = "entryeast"
          }
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 388,
          width = 134,
          height = 90,
          rotation = 0,
          opacity = 1,
          gid = 329,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "beachtable",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 388,
          width = 134,
          height = 90,
          rotation = 0,
          opacity = 1,
          gid = 329,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 8,
          name = "spawn",
          type = "",
          shape = "point",
          x = 40,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 12,
      id = 11,
      name = "treeup",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        139, 140, 139, 140, 139, 140, 139, 140, 139, 140, 139, 140, 139, 140, 139, 140, 139, 140, 139, 142, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "objects_beachwater",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 14,
          name = "beachwater",
          type = "",
          shape = "rectangle",
          x = 810,
          y = 0,
          width = 400,
          height = 480,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects_overlay",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 13,
          name = "hometowndaynight",
          type = "",
          shape = "point",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
