return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 48,
  height = 36,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 9,
  nextobjectid = 120,
  properties = {
    ["border"] = "leaves",
    ["inside"] = true,
    ["light"] = true,
    ["music"] = "deltarune/noelle_house_wip"
  },
  tilesets = {
    {
      name = "hometownobjects",
      firstgid = 1,
      filename = "../../../../../tilesets/hometownobjects.tsx",
      exportfilename = "../../../../../tilesets/hometownobjects.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../../../assets/sprites/world/maps/hometown/noellehouse/main.png",
      id = 2,
      name = "bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "polygon",
          x = 1560,
          y = 1000,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 120, y = 120 },
            { x = 120, y = 0 }
          },
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1360,
          y = 782,
          width = 80,
          height = 218,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 960,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 280,
          width = 280,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 280,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 400,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 280,
          width = 40,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 400,
          width = 40,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 680,
          width = 210,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1120,
          width = 40,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 1120,
          width = 40,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1360,
          width = 560,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1180,
          y = 1328,
          width = 60,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1328,
          width = 40,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 1328,
          width = 320,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1120,
          width = 480,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "polygon",
          x = 160,
          y = 1120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 120, y = -120 },
            { x = 0, y = -120 }
          },
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 960,
          width = 240,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 680,
          width = 40,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 1120,
          width = 400,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 800,
          width = 640,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1146,
          y = 960,
          width = 134,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 960,
          width = 88,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 840,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 840,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 792,
          y = 960,
          width = 290,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 680,
          width = 88,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 712,
          y = 680,
          width = 136,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 680,
          width = 88,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1354,
          y = 680,
          width = 86,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 680,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 1176,
          width = 160,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1096,
          y = 1180,
          width = 78,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 750,
          y = 1182,
          width = 78,
          height = 78,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1514,
          y = 1000,
          width = 22,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 1000,
          width = 22,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 588,
          y = 720,
          width = 22,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 818,
          y = 1082,
          width = 276,
          height = 42,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "polygon",
          x = 1050,
          y = 1052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 40 },
            { x = 40, y = 40 }
          },
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "polygon",
          x = 864,
          y = 1052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 40 },
            { x = -40, y = 40 }
          },
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 1052,
          width = 186,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 410,
          y = 990,
          width = 62,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects_belowparty",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1408,
          y = 1024,
          width = 86,
          height = 52,
          rotation = 0,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 300,
          y = 1024,
          width = 86,
          height = 52,
          rotation = 0,
          gid = 131,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 28,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 672,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "light/hometown/noellehouse/dess",
            ["marker"] = "entry",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 61,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 680,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cond"] = "Game:hasPartyMember(\"noelle\")",
            ["cutscene"] = "noellehouse.dess_blocker",
            ["solid"] = true
          }
        },
        {
          id = 36,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 672,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "light/hometown/noellehouse/bathroom",
            ["marker"] = "spawn",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 37,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 952,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "light/hometown/noellehouse/kitchen",
            ["marker"] = "entry",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 43,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1600,
          y = 1030,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "down",
            ["map"] = "light/hometown/town_noellehouse",
            ["marker"] = "entrynoellehouse",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 38,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 952,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "light/hometown/noellehouse/closet",
            ["marker"] = "spawn",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 30,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 672,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "light/hometown/noellehouse/noelle",
            ["marker"] = "entry",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 1274,
          width = 160,
          height = 110,
          rotation = 0,
          gid = 112,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 744,
          y = 1268,
          width = 84,
          height = 102,
          rotation = 0,
          gid = 109,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1096,
          y = 1268,
          width = 84,
          height = 102,
          rotation = 0,
          gid = 110,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 810,
          y = 1136,
          width = 292,
          height = 112,
          rotation = 0,
          gid = 108,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 1168,
          y = 280,
          width = 64,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "noellehouse.door"
          }
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 978,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1090,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1190,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 878,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 772,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 668,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 602,
          y = 586,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 708,
          y = 586,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 808,
          y = 586,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 918,
          y = 586,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1194,
          y = 586,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1302,
          y = 586,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1170,
          y = 182,
          width = 56,
          height = 32,
          rotation = 0,
          gid = 126,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1014,
          y = 304,
          width = 74,
          height = 70,
          rotation = 0,
          gid = 128,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 726,
          y = 720,
          width = 108,
          height = 108,
          rotation = 0,
          gid = 130,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "dancing_santa",
          type = "",
          shape = "rectangle",
          x = 1426,
          y = 902,
          width = 52,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {
            ["santa_type"] = 0
          }
        },
        {
          id = 101,
          name = "dancing_santa",
          type = "",
          shape = "rectangle",
          x = 316,
          y = 902,
          width = 52,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {
            ["santa_type"] = 1
          }
        },
        {
          id = 102,
          name = "dancing_santa",
          type = "",
          shape = "rectangle",
          x = 936,
          y = 616,
          width = 52,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {
            ["santa_type"] = 2
          }
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1170,
          y = 912,
          width = 56,
          height = 32,
          rotation = 0,
          gid = 126,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 650,
          y = 912,
          width = 56,
          height = 32,
          rotation = 0,
          gid = 126,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 456,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 250,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1438,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1540,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 866,
          y = 952,
          width = 56,
          height = 30,
          rotation = 0,
          gid = 129,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 112,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 756,
          y = 636,
          width = 50,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's Noelle's absurdly dangerous ninja weapon collection.)"
          }
        },
        {
          id = 114,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 1034,
          y = 254,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a heart or human-soul shaped pillow,[wait:5] depending on your opinion.)"
          }
        },
        {
          id = 115,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 870,
          y = 962,
          width = 52,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a thermostat. The only option is cold.)"
          }
        },
        {
          id = 116,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 406,
          y = 942,
          width = 68,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a fridge containing lots of greens and bottled water.)"
          }
        },
        {
          id = 117,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 906,
          y = 1168,
          width = 94,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (Just an empty table.)"
          }
        },
        {
          id = 118,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 202,
          y = 998,
          width = 32,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (The house's back door.)[wait:5]\n* (Somehow,[wait:5] it's locked.)"
          }
        },
        {
          id = 119,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 1156,
          y = 648,
          width = 54,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a tree that would potentially fall down if you climbed it.)"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 27,
          name = "entryeast",
          type = "",
          shape = "point",
          x = 1560,
          y = 1054,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "entrydess",
          type = "",
          shape = "point",
          x = 880,
          y = 746,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "entrynoelle",
          type = "",
          shape = "point",
          x = 680,
          y = 744,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "spawn",
          type = "",
          shape = "point",
          x = 1322,
          y = 744,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "entrykitchen",
          type = "",
          shape = "point",
          x = 1114,
          y = 1026,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "entrycloset",
          type = "",
          shape = "point",
          x = 760,
          y = 1022,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects_plants",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 1120,
          width = 290,
          height = 38,
          rotation = 0,
          gid = 111,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 350,
          y = 1120,
          width = 290,
          height = 38,
          rotation = 0,
          gid = 111,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
