return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 8,
  nextobjectid = 35,
  properties = {
    ["border"] = "elevator"
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 240,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 201,
          y = 200,
          width = 240,
          height = 41,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 240,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 360,
          width = 80,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 360,
          width = 80,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 6,
          name = "elevatorbuttons",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 480,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "intro/lab_reception",
            ["marker"] = "entry_elevator",
            ["sound"] = "elecdoor_close"
          }
        },
        {
          id = 29,
          name = "elevator",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["color_1"] = "#ff321fc3",
            ["color_10"] = "#ff00c800",
            ["color_11"] = "#ffffb15e",
            ["color_12"] = "#ffb18779",
            ["color_2"] = "#ff4429ff",
            ["color_3"] = "#ff97caf7",
            ["color_4"] = "#ff2368b8",
            ["color_5"] = "#ff913645",
            ["color_6"] = "#ff6aadff",
            ["color_7"] = "#ff373887",
            ["color_8"] = "#ff4429ff",
            ["color_9"] = "#ffffff00",
            ["cutscene_7"] = "broken_elevator",
            ["dest_1"] = "intro/lab_reception",
            ["dest_10"] = "deoxtest",
            ["dest_11"] = "evergroves/start",
            ["dest_12"] = "dirtworld/dirtworld",
            ["dest_2"] = "floor1/main",
            ["dest_3"] = "floor2/main_1",
            ["dest_4"] = "floorcyber/pre_elevator",
            ["dest_5"] = "floortv/pre_elevator",
            ["dest_6"] = "floorchurch/pre_elevator",
            ["dest_7"] = "nothing",
            ["dest_8"] = "seal_room/seal_room_1",
            ["dest_9"] = "tritraland/entrance",
            ["length_1"] = 140,
            ["length_10"] = 40,
            ["length_11"] = 40,
            ["length_12"] = 38,
            ["length_2"] = 40,
            ["length_3"] = 40,
            ["length_4"] = 40,
            ["length_5"] = 40,
            ["length_6"] = 40,
            ["length_7"] = 40,
            ["length_8"] = 40,
            ["length_9"] = 40,
            ["mod_1"] = "dpr_pit_dlc",
            ["name_1"] = "The Dark Pit",
            ["name_10"] = "Deoxtest",
            ["name_11"] = "Evergroves",
            ["name_12"] = "Dirt World",
            ["name_2"] = "Floor 1",
            ["name_3"] = "Floor 2",
            ["name_4"] = "Cyber Floor",
            ["name_5"] = "TV Floor",
            ["name_6"] = "Sanctuary Floor",
            ["name_7"] = "Nowhere",
            ["name_8"] = "Room",
            ["name_9"] = "TritraLand"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 5,
          name = "entry",
          type = "",
          shape = "point",
          x = 320,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "buttons",
          type = "",
          shape = "point",
          x = 380,
          y = 260,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "spawn",
          type = "",
          shape = "point",
          x = 320,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "entry_up",
          type = "",
          shape = "point",
          x = 320,
          y = 260,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
