return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 36,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 14,
  nextobjectid = 121,
  properties = {
    ["border"] = "green_room",
    ["music"] = "deltarune/greenroom_detune",
    ["name"] = "TV Floor - Green Room",
    ["quietpipis"] = true
  },
  tilesets = {
    {
      name = "ch3_dw_tvland_stage",
      firstgid = 1,
      filename = "../../../tilesets/ch3_dw_tvland_stage.tsx"
    },
    {
      name = "tvland_objects",
      firstgid = 370,
      filename = "../../../tilesets/floortv_objects.tsx",
      exportfilename = "../../../tilesets/floortv_objects.lua"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_floor",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 16,
          name = "greenroom_floor",
          type = "",
          shape = "rectangle",
          x = 10,
          y = 10,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 36,
      height = 12,
      id = 1,
      name = "floor",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
        36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36,
        36, 36, 0, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 259, 36, 36,
        36, 36, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 36, 36,
        36, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 36,
        36, 36, 36, 36, 36, 36, 36, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 36, 36, 36, 36, 36, 36, 36,
        36, 36, 36, 36, 36, 36, 36, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 36, 36, 36, 36, 36, 36, 36,
        36, 36, 36, 36, 36, 36, 36, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 36, 36, 36, 36, 36, 36, 36,
        36, 36, 36, 36, 36, 36, 36, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 36, 36, 36, 36, 36, 36, 36,
        36, 36, 36, 36, 36, 36, 36, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 236, 36, 36, 36, 36, 36, 36, 36,
        36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects_below",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "greenroom_wall",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 40,
          width = 640,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {
            ["fromamt"] = 0,
            ["shines"] = false,
            ["vines"] = false
          }
        },
        {
          id = 39,
          name = "greenroom_wall",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 40,
          width = 640,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {
            ["fromamt"] = 0,
            ["shines"] = false,
            ["vines"] = false
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects_below_2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 38,
          y = 240,
          width = 82,
          height = 204,
          rotation = 0,
          gid = 370,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1320,
          y = 240,
          width = 82,
          height = 204,
          rotation = 0,
          gid = 2147484018,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 401,
          y = 169,
          width = 60,
          height = 88,
          rotation = 0,
          gid = 374,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 340,
          width = 280,
          height = 100,
          rotation = 0,
          gid = 372,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 340,
          width = 280,
          height = 100,
          rotation = 0,
          gid = 373,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 387,
          y = 434,
          width = 16,
          height = 12,
          rotation = 0,
          gid = 380,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 407,
          y = 437,
          width = 32,
          height = 30,
          rotation = 0,
          gid = 381,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 443,
          y = 434,
          width = 16,
          height = 12,
          rotation = 0,
          gid = 380,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 550,
          y = 160,
          width = 390,
          height = 120,
          rotation = 0,
          gid = 378,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 160,
          width = 92,
          height = 146,
          rotation = 0,
          gid = 389,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1001,
          y = 160,
          width = 76,
          height = 104,
          rotation = 0,
          gid = 390,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "objects_dessim_door_a",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1320,
          y = 240,
          width = 82,
          height = 204,
          rotation = 0,
          gid = 403,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "interactable",
          type = "",
          shape = "polygon",
          x = 1320,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 80, y = 80 },
            { x = 80, y = 40 },
            { x = 0, y = -40 }
          },
          properties = {
            ["cutscene"] = "tvfloor.dessimation_tenna_door",
            ["solid"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "objects_dessim_door_b",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1320,
          y = 240,
          width = 82,
          height = 204,
          rotation = 0,
          gid = 404,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "script",
          type = "",
          shape = "polygon",
          x = 1320,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 80, y = 80 },
            { x = 80, y = 40 },
            { x = 0, y = -40 }
          },
          properties = {
            ["cutscene"] = "tvfloor.dessimation_tenna_scene",
            ["once"] = false
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "objects_base",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 106,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 550,
          y = 120,
          width = 390,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (Doesn't seem like anyone's here...)"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 440,
          width = 116,
          height = 102,
          rotation = 0,
          gid = 371,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 804,
          y = 440,
          width = 116,
          height = 102,
          rotation = 0,
          gid = 371,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 440,
          width = 160,
          height = 40,
          rotation = 0,
          gid = 377,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 273,
          y = 454,
          width = 70,
          height = 94,
          rotation = 0,
          gid = 2147484024,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1100,
          y = 454,
          width = 70,
          height = 94,
          rotation = 0,
          gid = 376,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 280,
          width = 280,
          height = 40,
          rotation = 0,
          gid = 387,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 280,
          width = 280,
          height = 40,
          rotation = 0,
          gid = 388,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 404,
          y = 397,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["flagcheck"] = "!can_kill",
            ["text1"] = "* (Stars ripple on the walls like soft music.)",
            ["text2"] = "* (You're filled with the power of relaxation.)"
          }
        },
        {
          id = 72,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 660,
          y = 410,
          width = 120,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "tvfloor.greenroomplatter",
            ["solid"] = true
          }
        },
        {
          id = 77,
          name = "greenroom_platter",
          type = "",
          shape = "rectangle",
          x = 670,
          y = 368,
          width = 100,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 80,
          width = 76,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a door.)[wait:5]\n* (It's locked.)"
          }
        },
        {
          id = 83,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 120,
          width = 90,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's the cooler door.)[wait:5]\n* (It's currently locked.)"
          }
        },
        {
          id = 89,
          name = "transition",
          type = "",
          shape = "polygon",
          x = 120,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -80, y = 80 },
            { x = -80, y = 40 },
            { x = 0, y = -40 }
          },
          properties = {
            ["exit_delay"] = 0.3,
            ["exit_sound"] = "doorclose",
            ["map"] = "floortv/legacy_corridors",
            ["marker"] = "entry_greenroom",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 90,
          name = "transition",
          type = "",
          shape = "polygon",
          x = 1320,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 80, y = 80 },
            { x = 80, y = 40 },
            { x = 0, y = -40 }
          },
          properties = {
            ["exit_delay"] = 0.3,
            ["exit_sound"] = "doorclose",
            ["map"] = "floortv/tenna_room",
            ["marker"] = "entry_greenroom",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 93,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 404,
          y = 397,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["flagcheck"] = "can_kill",
            ["text1"] = "* (The room is quiet,[wait:5] with nobody left to enjoy it...)",
            ["text2"] = "* (You feel a sense of emptiness.)"
          }
        },
        {
          id = 95,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1000.75,
          y = 123.67,
          width = 76.0384,
          height = 39.4545,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_delay"] = 0.3,
            ["exit_sound"] = "doorclose",
            ["map"] = "floortv/dump_corridors",
            ["marker"] = "entry_greenroom",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 103,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 694,
          y = 62,
          width = 92,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "tvfloor.exit_rambs_room",
            ["once"] = false
          }
        },
        {
          id = 109,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 401,
          y = 128.25,
          width = 60,
          height = 40.75,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "tvfloor.green_vending",
            ["solid"] = false
          }
        },
        {
          id = 118,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 400,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "tvfloor.greenroomracingtv",
            ["solid"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_barabove",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 550,
          y = 160,
          width = 390,
          height = 120,
          rotation = 0,
          gid = 379,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 36,
      height = 12,
      id = 6,
      name = "above",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 36, 36, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "base_collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 240,
          width = 240,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 280,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 440,
          width = 880,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1160,
          y = 240,
          width = 40,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1200,
          y = 240,
          width = 200,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 120,
          width = 1200,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 256,
          width = 80,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 256,
          width = 200,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 256,
          width = 200,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 256,
          width = 80,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 400,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 401,
          y = 160,
          width = 60,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "ramb_collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 574,
          y = 72,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 72,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 142,
          width = 360,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 904,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 86,
          name = "entry_left",
          type = "",
          shape = "point",
          x = 140,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "entry_right",
          type = "",
          shape = "point",
          x = 1260,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "entry_dump",
          type = "",
          shape = "point",
          x = 1040,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "entry_ramb",
          type = "",
          shape = "point",
          x = 739,
          y = 138,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "spawn",
          type = "",
          shape = "point",
          x = 424,
          y = 390,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
